### ISSUE TITLE
[Support]: Compatibility with ZeroTier 1.12.x

### ISSUE THREAD

**Issue by imyller** [sinamics/ztnet#102]
### 📝 Describe the Problem You Are Having

Looks like ZTNET has some compatibility issues with the new ZeroTier 1.12.0 release:

- **Network modifications result in HTTP/500 network_update failure**
- Network create works
- Network delete works

### 🔖 Version

latest

### 💻 Operating System

None

**Comment by sinamics** [comment]
I have not tested 1.12, nor am i familar with the changelog.
Will look into it when i get time.

**Comment by imyller** [comment]
No info on API changes in general release notes @ https://github.com/zerotier/ZeroTierOne/blob/dev/RELEASE-NOTES.md
```
2023-08-23 -- Version 1.12.0

- Experimental Windows ARM64 support
- Fix numerous sleep/wake issues on macOS and other platforms
- Faster recovery after changes to physical network settings
- Prometheus compatible metrics support!
- Fix full tunnel mode on recent macOS versions
- Numerous macOS DNS fixes
- 10-30% speed improvement on Linux
```

More detailed commit summary here:
https://github.com/zerotier/ZeroTierOne/releases/tag/1.12.0

**Comment by sinamics** [comment]
I opened an issue at zt repo.
https://github.com/zerotier/ZeroTierOne/issues/2108

**Comment by BingMeng** [comment]
After i update to zerotier 1.12.1, the problem still here.

They haven't test it before publishing 👎

**Comment by sinamics** [comment]
Hmm. I tested 1.12.1 using curl earlier today, and it worked. Will test the latest docker build later this evening

**Comment by sinamics** [comment]
@f0re1gnKey you are right. They fixed the network update api, but members api returning diffrent datatypes than before.
https://github.com/zerotier/ZeroTierOne/issues/2114

**Comment by VMCoud** [comment]
> 你是对的。他们修复了网络更新 api，但成员 api 返回的数据类型与以前不同。零[层/零层一#2114](https://github.com/zerotier/ZeroTierOne/issues/2114)

https://github.com/dec0dOS/zero-ui/commit/856682bad1ccd46970681e45bea8a992043c38f4#diff-36a4ff1e603607f1af1e6a0aaa66991dafdcb5d4b303f03a7521c898afcfe9c1

**Comment by sinamics** [comment]
@VMCoud, I'm holding off on making any modifications to ZTNet until ZeroTier releases a fix for the current bug. Once that happens, I'll proceed with testing and updates.

**Comment by v808comd** [comment]
@f0re1gnKey  ZerotierFix 有个实时构建的版本可以使用非官方的 planet。https://github.com/kaaass/ZerotierFix/suites/15589696211/artifacts/889595892

**Comment by sinamics** [comment]
Closing this issue for now. If anyone encounters further problems, kindly open a new issue for discussion.
