### ISSUE TITLE
[Support]: 0.3.6 发现一个小 bug 

### ISSUE THREAD

**Issue by v808comd** [sinamics/ztnet#105]
### 📝 Describe the Problem You Are Having

docker-compose.yml  文件中，将 NEXTAUTH_URL: "http://localhost:3000"   修改为 NEXTAUTH_URL: "http://ip:3000" 后，退出登录后不能回到登录界面。
注册后也不能进入界面。

### 🔖 Version

0.3.6

### 💻 Operating System

None

**Comment by sinamics** [comment]
Please try to clean browser cache. 
When you logout, you should be redirected to `http://ip:3000/auth/login`

If you still have issues, i need to know more about your system.

Browser:
Operating System:

Also, can you describe what you see in the browser when you logout?
And the docker logs would be helpfull:
`docker logs ztnet`

**Comment by v808comd** [comment]
- info Loaded env from /app/.env
Listening on port 3000 url: http://379579bc3bd0:3000
- info Loaded env from /app/.env
[next-auth][error][CLIENT_FETCH_ERROR]
https://next-auth.js.org/errors#client_fetch_error fetch failed {
  error: {
    message: 'fetch failed',
    stack: 'TypeError: fetch failed\n' +
      '    at Object.fetch (node:internal/deps/undici/undici:11576:11)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
    name: 'TypeError'
  },
  url: 'http://218.60.97.186:3000/api/auth/session',
  message: 'fetch failed'
}
[next-auth][error][CLIENT_FETCH_ERROR]
https://next-auth.js.org/errors#client_fetch_error fetch failed {
  error: {
    message: 'fetch failed',
    stack: 'TypeError: fetch failed\n' +
      '    at Object.fetch (node:internal/deps/undici/undici:11576:11)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
    name: 'TypeError'
  },
  url: 'http://218.60.97.186:3000/api/auth/session',
  message: 'fetch failed'
}
[next-auth][error][CLIENT_FETCH_ERROR]
https://next-auth.js.org/errors#client_fetch_error fetch failed {
  error: {
    message: 'fetch failed',
    stack: 'TypeError: fetch failed\n' +
      '    at Object.fetch (node:internal/deps/undici/undici:11576:11)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
    name: 'TypeError'
  },
  url: 'http://218.60.97.186:3000/api/auth/session',
  message: 'fetch failed'
}
[next-auth][error][CLIENT_FETCH_ERROR]
https://next-auth.js.org/errors#client_fetch_error fetch failed {
  error: {
    message: 'fetch failed',
    stack: 'TypeError: fetch failed\n' +
      '    at Object.fetch (node:internal/deps/undici/undici:11576:11)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
    name: 'TypeError'
  },
  url: 'http://218.60.97.186:3000/api/auth/session',
  message: 'fetch failed'
}
[next-auth][error][CLIENT_FETCH_ERROR]
https://next-auth.js.org/errors#client_fetch_error fetch failed {
  error: {
    message: 'fetch failed',
    stack: 'TypeError: fetch failed\n' +
      '    at Object.fetch (node:internal/deps/undici/undici:11576:11)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
    name: 'TypeError'
  },
  url: 'http://218.60.97.186:3000/api/auth/session',
  message: 'fetch failed'
}
[next-auth][error][CLIENT_FETCH_ERROR]
https://next-auth.js.org/errors#client_fetch_error fetch failed {
  error: {
    message: 'fetch failed',
    stack: 'TypeError: fetch failed\n' +
      '    at Object.fetch (node:internal/deps/undici/undici:11576:11)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
    name: 'TypeError'
  },
  url: 'http://218.60.97.186:3000/api/auth/session',
  message: 'fetch failed'
}
[next-auth][error][CLIENT_FETCH_ERROR]
https://next-auth.js.org/errors#client_fetch_error fetch failed {
  error: {
    message: 'fetch failed',
    stack: 'TypeError: fetch failed\n' +
      '    at Object.fetch (node:internal/deps/undici/undici:11576:11)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
    name: 'TypeError'
  },
  url: 'http://218.60.97.186:3000/api/auth/session',
  message: 'fetch failed'
}
[next-auth][error][CLIENT_FETCH_ERROR]
https://next-auth.js.org/errors#client_fetch_error fetch failed {
  error: {
    message: 'fetch failed',
    stack: 'TypeError: fetch failed\n' +
      '    at Object.fetch (node:internal/deps/undici/undici:11576:11)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
    name: 'TypeError'
  },
  url: 'http://218.60.97.186:3000/api/auth/session',
  message: 'fetch failed'
}

**Comment by v808comd** [comment]
首次注册管理员后跳转到登陆界面，会卡在 http://ip:3000/auth/login  页面。

![20230827021323](https://github.com/sinamics/ztnet/assets/65583931/f9538c05-5c3f-40ae-8c57-4aafad801827)

**Comment by sinamics** [comment]
Can you try to clean cache. `Ctrl + Shift + R`, or use incognito
Did you try another browser?

**Comment by v808comd** [comment]
我是清理了缓存的。
http://218.60.97.186:3000/
是开放注册的，您可以测试一下。

**Comment by sinamics** [comment]
Thx. Can you post your docker-compose.yml file.

**Comment by v808comd** [comment]
version: "3.1"
services:
  postgres:
    image: postgres:15.2-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ztnet
    volumes:
      - /opt/volumes/postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  zerotier:
    image: zyclonite/zerotier:1.10.6
    hostname: zerotier
    container_name: zerotier
    restart: unless-stopped
    volumes:
      - /opt/volumes/zerotier:/var/lib/zerotier-one
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - app-network
    ports:
      - "9993:9993/udp"
    environment:
      - ZT_OVERRIDE_LOCAL_CONF=true
      - ZT_ALLOW_MANAGEMENT_FROM=172.31.255.0/29

  ztnet:
    image: sinamics/ztnet:latest
    container_name: ztnet
    working_dir: /app
    volumes:
      - /opt/volumes/zerotier:/var/lib/zerotier-one
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      NEXTAUTH_URL: "http://218.60.97.186:3000"
      NEXTAUTH_SECRET: "random_secret"
    networks:
      - app-network
    links:
      - postgres
    depends_on:
      - postgres
      - zerotier
volumes:
  zerotier:
  postgres-data:

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.255.0/29

**Comment by v808comd** [comment]
`version: "3.1"
services:
  postgres:
    image: postgres:15.2-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ztnet
    volumes:
      - /opt/volumes/postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  zerotier:
    image: zyclonite/zerotier:1.10.6
    hostname: zerotier
    container_name: zerotier
    restart: unless-stopped
    volumes:
      - /opt/volumes/zerotier:/var/lib/zerotier-one
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - app-network
    ports:
      - "9993:9993/udp"
    environment:
      - ZT_OVERRIDE_LOCAL_CONF=true
      - ZT_ALLOW_MANAGEMENT_FROM=172.31.255.0/29

  ztnet:
    image: sinamics/ztnet:latest
    container_name: ztnet
    working_dir: /app
    volumes:
      - /opt/volumes/zerotier:/var/lib/zerotier-one
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      NEXTAUTH_URL: "http://218.60.97.186:3000"
      NEXTAUTH_SECRET: "random_secret"
    networks:
      - app-network
    links:
      - postgres
    depends_on:
      - postgres
      - zerotier
volumes:
  zerotier:
  postgres-data:

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.255.0/29`

**Comment by sinamics** [comment]
try to add these in docker-compose.yml

```yml
NEXTAUTH_URL: "http://218.60.97.186:3000"
NEXTAUTH_URL_INTERNAL: "http://localhost:3000"
```

**Comment by v808comd** [comment]
Thx，Added NEXTAUTH_URL_INTERNAL: "http://localhost:3000"   ，Perfect solution to the problem!

**Comment by v808comd** [comment]
创建 planet后，查看 docker logs ztnet . 其中有这个提示：
2023/08/27 03:32:03 read world signing key failed:  open previous.c25519: no such file or directory  ,  open current.c25519: no such file or directory
2023/08/27 03:32:03 preflight check error occurred, but still can proceed.

**Comment by sinamics** [comment]
>Thx，Added NEXTAUTH_URL_INTERNAL: "http://localhost:3000/" ，Perfect solution to the problem!

Perfect. Thank you for letting me test on your server. 👍 


> 2023/08/27 03:32:03 read world signing key failed: open previous.c25519: no such file or directory , open current.c25519: no such.
> 2023/08/27 03:32:03 preflight check error occurred, but still can proceed.

These are normal when you create a new planet. It willl generate new certificates `previous.c25519` & `current.c25519`.
If you upload a config that has these files included, you will not get this error.
