### ISSUE TITLE
[Support]: IP Assigment panel can not collapse after click IPv6 tab

### ISSUE THREAD

**Issue by livelazily** [sinamics/ztnet#109]
### 📝 Describe the Problem You Are Having

![test](https://github.com/sinamics/ztnet/assets/449935/7d929027-da65-4c0c-901f-eef1190383ae)

### 🔖 Version

0.3.6

### 💻 Operating System

None

**Comment by sinamics** [comment]
Could you inform which browser and OS you are using?

**Comment by livelazily** [comment]
@sinamics 
Firefox 117
macOS 12.6.8
