### ISSUE TITLE
[Feature Request]: Adding new users in the backend

### ISSUE THREAD

**Issue by VMCoud** [sinamics/ztnet#112]
### 🚀 Feature Summary

  增加备注  用户到期时间  

### 💡 Willing to Contribute

Yes, I could help with testing

**Comment by sinamics** [comment]
Hi
Could you please clarify your feature request in English? Additionally, could you provide a use case to better understand the functionality you are requesting?

**Comment by v808comd** [comment]
He may be hoping for a "user expiration restriction" feature that can suspend the user's network after expiration. And I hope to add comments to the user list.

**Comment by VMCoud** [comment]
> Hi Could you please clarify your feature request in English? Additionally, could you provide a use case to better understand the functionality you are requesting?

Hello, can you add the functions of adding users manually in the background, setting user notes, setting user timeout, and automatically stopping the authorization of devices in the network list when they expire?

**Comment by sinamics** [comment]
Will be available from version 0.4.0
http://10.0.0.217:4000/Rest%20Api/User/post-new-user

**Comment by VMCoud** [comment]
> Will be available from version 0.4.0
> http://10.0.0.217:4000/Rest%20Api/User/post-new-user

Can the user's network still be used after expiration

**Comment by sinamics** [comment]
Network is still available, but all peers will be de-authorized
