### ISSUE TITLE
[Support]: Planet config adjustment

### ISSUE THREAD

**Issue by BingMeng** [sinamics/ztnet#113]
### 📝 Describe the Problem You Are Having

The official planetID(149604618) and birthID(1567191349589) can function normally, so don't restrict setting them. Some third-party clients must use official ID to load the planet file. eg: **https://github.com/kaaass/ZerotierFix/issues/60**

When the planet have two external ips and have different port, the primaryPort will set the last ip port. It should set secondaryPort too, or let users handle the local.conf by themselves.

### 🔖 Version

v0.3.6

### 💻 Operating System

None

**Comment by sinamics** [comment]
Thank you for the feedback, much appreciated.

> The official planetID(149604618) and birthID(1567191349589) can function normally, so don't restrict setting them. Some third-party clients must use official ID to load the planet file. eg: https://github.com/kaaass/ZerotierFix/issues/60

Ah, did not know that. Will allow these in next version.

> When the planet have two external ips and have different port, the primaryPort will set the last ip port. It should set secondaryPort too, or let users handle the local.conf by themselves.

Is this correct?
```bash
primaryPort  => first ip/port
secondaryPort => last ip/port 
```

> or let users handle the local.conf by themselves

i want to change those values automatically if possible.  
Currently it just parses the conf file and changes the primaryPort values. 
It will not make any other changes to other paramteres in the local.conf file.

**Comment by v808comd** [comment]
I also discovered this issue,

**Comment by BingMeng** [comment]
> Thank you for the feedback, much appreciated.
> 
> > The official planetID(149604618) and birthID(1567191349589) can function normally, so don't restrict setting them. Some third-party clients must use official ID to load the planet file. eg: [kaaass/ZerotierFix#60](https://github.com/kaaass/ZerotierFix/issues/60)
> 
> Ah, did not know that. Will allow these in next version.
> 
> > When the planet have two external ips and have different port, the primaryPort will set the last ip port. It should set secondaryPort too, or let users handle the local.conf by themselves.
> 
> Is this correct?
> 
> ```shell
> primaryPort  => first ip/port
> secondaryPort => last ip/port 
> ```
> 
> > or let users handle the local.conf by themselves
> 
> i want to change those values automatically if possible. Currently it just parses the conf file and changes the primaryPort values. It will not make any other changes to other paramteres in the local.conf file.

Yes. The first port set as primaryPort, the second one set as secondaryPort.
The full local.conf description is under here. https://github.com/zerotier/ZeroTierOne/blob/dev/service/README.md
