### ISSUE TITLE
[Support]: Sign-up still available after user registration is disabled

### ISSUE THREAD

**Issue by imyller** [sinamics/ztnet#117]
### 📝 Describe the Problem You Are Having

Sign-up links and registration page are still available after user registration is disabled.

<img width="906" alt="signup-bug" src="https://github.com/sinamics/ztnet/assets/1898870/c78baeeb-acf0-4db1-a6cf-66abaaa4a6b2">

<img width="605" alt="signup-bug2" src="https://github.com/sinamics/ztnet/assets/1898870/090f39e4-8865-42ea-a2cf-5d9d466bfe42">

<img width="490" alt="signup-bug3" src="https://github.com/sinamics/ztnet/assets/1898870/4218f79a-b313-4e43-84c5-25a89357cd41">

### 🔖 Version

0.3.7

### 💻 Operating System

Debian

**Comment by sinamics** [comment]
Signup page is accessible; however, attempting to register will result in an error. If you prefer, I can disable the registration feature and remove the signup page altogether.

**Comment by imyller** [comment]
I assumed that disabling user registration in the settings would also hide the public UI interface offering sign-up/registration.

As long as created invitation links are still accessible, it would be logical to hide public sign-up UI in this case.

**Comment by imyller** [comment]
This is bit off topic for this issue, but ..

Absolutely fantastic work with ZTNET! So far the best ZeroTier network management UI in my opinion.

Thank you!

**Comment by sinamics** [comment]
Thanks so much for the compliment. Really glad to hear you like it.
