### ISSUE TITLE
[Support]: IP addresses sorting issue

### ISSUE THREAD

**Issue by tinola** [sinamics/ztnet#129]
### 📝 Describe the Problem You Are Having

Hi :)

IP addresses are not correctly sorted on members list page.

![ip_sort](https://github.com/sinamics/ztnet/assets/3160125/e3505afa-f9e9-49ac-98a7-3db0940f42cb)

Click table header "Managed IP / Latency" to sort column with IP addresses in ascending/descending order.
I found some idea how to fix it using JS [here](https://stackoverflow.com/questions/48618635/require-sorting-on-ip-address-using-js), but I'm sure you'll find better solution :)

### 🔖 Version

v.0.3.8

### 💻 Operating System

Other

**Comment by sinamics** [comment]
Thx. Will be fixed.

**Comment by tinola** [comment]
Ekhm, and the "ID" column should be "hex-aware" sortable ;)
