### ISSUE TITLE
[Feature Request]: Enhance Page Titles, Members List Sorting, and Mobile Menu Interactions

### ISSUE THREAD

**Issue by tinola** [sinamics/ztnet#134]
### 🚀 Feature Summary

Visual enhancements ideas

### 📝 Detailed Description

Hello :)

Well, I'm not sure you'll kill me, but I have some ideas...

1) Page title browsing members list - I think it's better name it as network name rather than network ID.
Page title now:
ZTNET - <NETWORK_ID>
After change:
ZTNET - <NETWORK_NAME>

2) Members list page.
2.1) Possibility to save last state of table sorting and number of displayed members.
Now the defaults are:
-> sort table by ID in descending order
-> show 10 members
I don't know how to achieve it in most easy way, maybe set some cookies? or save user choices in PostgreSQL database?
2.2) Also in drop down form with values to show items (now from 10 to 50), there should be an option "All" to show all members on one page as well.
2.3) "Auth" column - when member is authorized we can click checkbox to remove authorization.
Idea: in case of member de-authorization, show confirmation popup "Are you sure? Yes/No".

3) Possibility to show/hide left menu.
Why? On mobile device (smartphone) in vertical position there is the "hamburger" icon to show left menu, tapping somewhere next to menu it hides, which is good.
Rotating mobile to horizontal position I can't hide left menu, so it takes 1/3 of screen.
I think some new icon to show/hide menu will do the trick :) Of course not only on mobile devices... 

Regards

### 💡 Willing to Contribute

None

**Comment by sinamics** [comment]
Thank you for these requests. 

> I'm not sure you'll kill me, but I have some ideas.

I appreciate any suggestions to improve the application. 👍 

I agree on all execpt the confirmation popup on member auth. 
Is it that critical to de-auth a member?  Just for my own experience, i de-auth and authorize member all the time, and adding a pop up would just add another mouse click into the chain. 

Im open for discussion though.

I will add in all other items.

**Comment by tinola** [comment]
> I agree on all execpt the confirmation popup on member auth.
> Is it that critical to de-auth a member? Just for my own experience, i de-auth and authorize member all the time, and adding a pop up would just add another mouse click into the chain.

Well, maybe it's not critical, but I accidentally deauthorized myself on my mobile device in some strange way by tapping on the web interface. Before I knew it, I lost connection with myself ;)
Just that's why I thought about additional protection against accidental deauthorization.

EDIT:
I call it SUE... Stupid User Exception ;)
Sometimes we can do anything to prevent SUE, so I think any deauthorization/removing/deleting anything should be preceded by confirmation "YES/NO"

**Comment by sinamics** [comment]
Got it, I see the issue.  Could probably add an on/off option for this in the user settings.

**Comment by tinola** [comment]
Hello,

I can't check all your changes because of compile error.

[build_failure.txt](https://github.com/sinamics/ztnet/files/12572523/build_failure.txt)

I'm on `main` branch.

**Comment by tinola** [comment]
Hello,

I can't check all your changes because of compile is not finishing.

[build_failure.txt](https://github.com/sinamics/ztnet/files/12572536/build_failure.txt)

I'm on `main` branch.

**Comment by sinamics** [comment]
Hi
You need to migrate db to update new values. 
`npx prisma migrate deploy`

However, there is a bug that i need to rectify, so i recommend that you wait until this has been fixed.

**Comment by tinola** [comment]
Sure! I'll wait.
Thanks :)

**Comment by sinamics** [comment]
@tinola You can test the lastet main now.
`git checkout main && git pull`

Then update database
`npx prisma migrate deploy`

I haven't conducted exhaustive testing yet, but feel free to try it out and share your feedback.  I'll thoroughly test everything before the next release.

**Comment by tinola** [comment]
OK, so pulled `main` branch and updated database. Unfortunately still does not compile.

[build_failure_#2.txt](https://github.com/sinamics/ztnet/files/12573368/build_failure_.2.txt)

**Comment by sinamics** [comment]
Are you sure you are fetching latest version? Try to stash any local changes before you git pull
`git stash save "Local changes before checkout"`

**Comment by tinola** [comment]
$ git stash save "Local changes before checkout"
No local changes to save

$ cat .git/HEAD
ref: refs/heads/main

 $ cat .git/ORIG_HEAD
77547db30fcced0723ad37c9b42aa359813f07bc

Hmm...

**Comment by sinamics** [comment]
Im not seeing that error on my side. 
However, i added and extra type as the error complains about. Pull latest and try again

**Comment by tinola** [comment]
Another build error:

[build_failure_#3.txt](https://github.com/sinamics/ztnet/files/12573573/build_failure_.3.txt)

But in other file than earlier.

**Comment by sinamics** [comment]
try now

**Comment by tinola** [comment]
Bingo! Compile finished successful :)

**Comment by tinola** [comment]
Right, again thank you for your outstanding job and last changes.
I found some minor errors.

1. On `User Settings` page when I click `Display warning on member De-Authorization` to set it true, just nothing happens.

Firefox Dev Console shows this:

![FF_dev_console](https://github.com/sinamics/ztnet/assets/3160125/f260f80a-c1d8-454b-a8f7-7410ace6ea06)

I'm sure that `UserOptions` table in database was successfully altered after `npx prisma migrate deploy` command.

2. Members list table - on every full page refresh (Ctrl+F5):
- the browser does remember pagesize 👍 
- the browser forgets what column it was sorted by

All other changes work perfectly ❤️

**Comment by sinamics** [comment]
> On User Settings page when I click Display warning on member De-Authorization to set it true, just nothing happens.

can you post the output of `npx prisma migrate deploy` ?

> the browser forgets what column it was sorted by

ah, yes. This feature has not been added yet. Will be fixed.

**Comment by tinola** [comment]
> can you post the output of `npx prisma migrate deploy` ?

Sure

[db_upd.txt](https://github.com/sinamics/ztnet/files/12574593/db_upd.txt)

**Comment by sinamics** [comment]
this logs shows that the emigration was deployed successfully. 
Did you try the webinterface after this command was exectued?

```yml
17 migrations found in prisma/migrations

Applying migration `20230910161252_authorize_warning`

The following migration have been applied:

migrations/
  └─ 20230910161252_authorize_warning/
    └─ migration.sql
    
 ```
 
 If no migration is applicable, it should just print
 ```bash
 17 migrations found in prisma/migrations
```

**Comment by tinola** [comment]
Forget to mention, that output was from early morning today. I used `npx prisma migrate deploy` **before compilation problems**.

Now it stays:

```
$ npx prisma migrate deploy
Warning Precompiled engine files are not available for freebsd13. Read more about building your own engines at https://pris.ly/d/build-engines
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "ztnet", schema "public" at "127.0.0.1:5432"

17 migrations found in prisma/migrations


No pending migrations to apply.
```

View from phpPgAdmin

![phppgadmin](https://github.com/sinamics/ztnet/assets/3160125/1d486baf-62a0-4bbe-89d9-998b6bbe4614)

**Comment by sinamics** [comment]
ok, then try this command `npx prisma generate`
Might be that local prisma agent is not aware of the changes.

Also restart the frontend, if you not already did so.

**Comment by tinola** [comment]
Yes! That did the trick :)
Applied commands:

```
npx prisma generate
rm -rf .next/
npm run build
cp -r .next/static .next/standalone/.next/ && cp -r public .next/standalone/
```
and problems gone away.

So, I can confirm working confirmation modal in case of de-authorizing member.

THX 👍

**Comment by sinamics** [comment]
@tinola i have added persistent table sorting and made some improvement on the inital page load.
Could you test the latest version. There is no DB changes so you only need to perform a pull.

**Comment by tinola** [comment]
I can confirm persistent sorting works on every available table in webUI, not only members list table.
Great!

If I come up with a new idea, I will let you know in the new FR :)
