### ISSUE TITLE
[Support]: PlanetID and BirthID created not correctly

### ISSUE THREAD

**Issue by BingMeng** [sinamics/ztnet#139]
### 📝 Describe the Problem You Are Having

The planetID and birthID created are not the value entered in ztnet, because the mkworld.config.json plRecommend was set to true. 

When it set to true, the mk-world will generate random ID instead of using the value we set.

```
{
    "rootNodes": [
        {
            "comments": "hidden",
            "identity": "hidden",
            "endpoints": [
                "hidden",
                "hidden"
            ]
        }
    ],
    "signing": [
        "previous.c25519",
        "current.c25519"
    ],
    "output": "planet.custom",
    "plID": 149604618,
    "plBirth": 1567191349589,
    "plRecommend": true
}
```

### 🔖 Version

v0.3.8

### 💻 Operating System

Debian

**Comment by sinamics** [comment]
Hm, im not able to re-produce this behaviour. 
When custom ID and Birth is used, the plRecommend is false in my mkworld.config.json

**Comment by sinamics** [comment]
@f0re1gnKey could you please inform how you were able to generate the wrong mkworld config so i can make get it sorted before the next release.

**Comment by BingMeng** [comment]
> 

This is my operations:
my planetId and birthId is official one,  birthId: 1567191349589,  planetId: 149604618
1. open the ztnet controller page  http://ztnet.example/admin?tab=controller
2. click [edit planet config], without modifying anything, click [update planet].
3. check the mkworld.config.json, plRecommand become true.
