### ISSUE TITLE
[Support]: I feel that ztnet can be tested in my production environment to further identify bugs

### ISSUE THREAD

**Issue by v808comd** [sinamics/ztnet#142]
### 📝 Describe the Problem You Are Having

So there are still some minor changes needed to address the following issues.

1. The registration/login page has not been translated into other languages,

Alternatively, the welcome message can be edited by the administrator. If the default language could be recognized through the user's browser, it would be even more perfect.

2. The dashboard display content can be edited by the administrator.

3. The current version does not seem to have a login timeout and exit. You can access the previous login at any time, which is not secure enough.

4. 'DELETE NETWORK' must be translated, as it may cause unpredictable consequences. Perhaps even better, only contacting the administrator can exercise this function.

There is another unclear point that members have an ipv6 address, but only ipv4 is displayed in the member list. On my.zerotier.com, ipv6 can be displayed

### 🔖 Version

0.3.8

### 💻 Operating System

None

**Comment by sinamics** [comment]
Hi
Like you said, it still some work to be done before version 1.0.0 

> The registration/login page has not been translated into other languages,
Alternatively, the welcome message can be edited by the administrator. If the default language could be recognized through the user's browser, it would be even more perfect.

I have been thinking about adding an admin defined welcome message. This is gives the admin more flexibillities.

> The dashboard display content can be edited by the administrator.

I want to add in metrics from the controller as the 1.12.x has /metric support. But please suggest what else we can add in the dashboard or if you have other ideas.

> The current version does not seem to have a login timeout and exit. You can access the previous login at any time, which is not secure enough.

Currently the session timeout is 30 days. Could add an option in admin menu for adjusting the expire time.

> 'DELETE NETWORK' must be translated, as it may cause unpredictable consequences. Perhaps even better, only contacting the administrator can exercise this function.

I will add translation for the delete network function. But i think the user who own the network should be eligible to delete it without admin approval, but im open for discussion.

> There is another unclear point that members have an ipv6 address, but only ipv4 is displayed in the member list. On my.zerotier.com, ipv6 can be displayed

ipv6 for central networks is currenlty not working. Will be fixed.

**Comment by v808comd** [comment]
> I want to add in metrics from the controller as the 1.12.x has /metric support. But please suggest what else we can add in the dashboard or if you have other ideas.

In general, administrators would like to see some intuitive indicators in the dashboard, such as the number of networks and active networks/users, as well as the number of active users/members and active members/hardware usage/server network usage...

> I will add translation for the delete network function. But i think the user who own the network should be eligible to delete it without admin approval, but im open for discussion.

Deleting the network is definitely a dangerous operation in a production environment. If the administrator accidentally operates, forgets to close the browser, or the account password is guessed by others, the result is unbearable. Perhaps verifying through email is also a good idea.

**Comment by imyller** [comment]
I've already deployed ZTNET to two production environments and the experience has been good so far.

For production environment the provided Docker Compose configuration sample alone might be a bit too simplistic, but with some additional tooling I'd say ZTNET itself is usable in production.

The work of @sinamics on this project has been absolute fantastic.

Surely there still is feature disparity between ZeroTier Central and ZTNET UI on some cases, but for common "road-warrior VPN" use case the current features are more than enough.

Going forward, I'd like to see an API interface for modifying networks and memberships -- and possibly as a followup to that a Terraform plugin allowing automatic provisioning of ZTNET controlled resources. That would be a killer feature.

**Comment by sinamics** [comment]
@v808comd for the security concern, we could add a env in docker-compose `SECURITY_MODE: strict`  that will set various confirmation by mail.  I dont want to add these as default. Will figure something out.

@imyller Glad to hear you liked it. 
Please let me know if you have suggestion to improve the docker-compose file. 
Im planing on adding in API support like Zerotier Central, but that will take some time to implement. Currently im focused on creating ztnet stable and bug free.
