### ISSUE TITLE
[Support]: Physical IP sorting issue

### ISSUE THREAD

**Issue by tinola** [sinamics/ztnet#145]
### 📝 Describe the Problem You Are Having

Hello,

Try to sort by physical IP (members list table). Something is wrong here.

### 🔖 Version

main branch

### 💻 Operating System

Other

**Comment by tinola** [comment]
Yes, now I can sort ascending and descending, but sorting seems to not work OK...
Please take a look:

![ip_sorting](https://github.com/sinamics/ztnet/assets/3160125/373c1363-eed8-4458-8588-48a0abf53186)

This column may contain a "Unknown" word in case of offline members, maybe that causes an issue?

**Comment by sinamics** [comment]
Thats odd, Its working fine on my side. Did you pull the latest version tag, or are you using latest main?

"unknown" will be equal to 0 in the sort function as the value is null. https://github.com/sinamics/ztnet/blob/64b7041feae5de86a16a5a1317785413094394d5/src/components/modules/table/memberHeaderColumns.tsx#L77

The sort function is just multiplying the accumulator by 256 for each octet and summing all bytes togheter to an Integer that will be sorted.
https://github.com/sinamics/ztnet/blob/64b7041feae5de86a16a5a1317785413094394d5/src/components/modules/table/memberHeaderColumns.tsx#L56-L60


![image](https://github.com/sinamics/ztnet/assets/7771916/509e4d78-a2c1-49a5-a6c6-41ffbd766813)

**Comment by tinola** [comment]
Hmm, that's very strange...
I've got latest `main` branch, built a few minutes ago and this is what i get

![sort_phy-ip](https://github.com/sinamics/ztnet/assets/3160125/072e86b7-8814-40de-9079-55341b6876ac)

Managed IPs are sorting OK.

Could you try standalone version on your FreeBSD test VM?

**Comment by sinamics** [comment]
Tested on frebsd now, and i do get the same behavior. 
Will look into that.

**Comment by sinamics** [comment]
@tinola test the latest main.

**Comment by tinola** [comment]
Hi,

`Physical IP` sorting is OK now, but try to sort `Managed IP / Latency` column... I see this:

![ip_mngd](https://github.com/sinamics/ztnet/assets/3160125/9bca0e03-39d3-4a66-9fe9-65ee9caae457)

**Comment by sinamics** [comment]
Thank you. will test more this weekend.

**Comment by sinamics** [comment]
Take 10 😄 
Test the latest main

**Comment by tinola** [comment]
Well, when you fixed the `Managed IP / Latency` sort, the `Physical IP` sort broke. Mysterious case... ;)

Latest `main` branch, `ztnet` as standalone app, FreeBSD as host system.

**Comment by sinamics** [comment]
strange. 
Can you test again now.

**Comment by tinola** [comment]
TADA! Now both columns sort OK.
Thanks 👍
