### ISSUE TITLE
[Support]: Create root/planet error message and themes

### ISSUE THREAD

**Issue by tinola** [sinamics/ztnet#146]
### 📝 Describe the Problem You Are Having

Hello,

I found 2 issues ;)

1. Since `ztnet` can be used as standalone application, an error message creating planet should be clarified, I mean remove `the docker volume mount`.

![error](https://github.com/sinamics/ztnet/assets/3160125/f9d654ec-42c7-49a2-a988-0dc6dd91dc6e)

Additionally, I think I mentioned... `ztnet` should recognize base operating system. Default ZT configuration paths are:
- `/var/lib/zerotier-one` for Linux based OS
- `/var/db/zerotier-one` for FreeBSD (I don't know if other BSDs have this path too)

One more question because I'm not sure - does **CREATE PLANET** (submit button) mean the same as _CREATE ROOT_ (a.k.a. _MOON_)?...

2. Choosing themes "**DARK**" and "**SYSTEM**" on top right of webUI seems to not change colours. They act as the same theme.

### 🔖 Version

main branch

### 💻 Operating System

Other

**Comment by sinamics** [comment]
Thx. 

- The root server is still in "work in progress" for the standalone version. 
- Correct zerotier path will be fixed.

> does CREATE PLANET (submit button) mean the same as CREATE ROOT (a.k.a. MOON)?

 "CREATE PLANET" button in the application will initiate the process to create a custom root server using the [mkworld tool](https://github.com/kmahyyg/ztncui-aio#usage). However, it's worth noting that my expertise on custom roots is limited. I never explored this side of zerotier, but i added this functionality based on this request https://github.com/sinamics/ztnet/issues/76

> Choosing themes "DARK" and "SYSTEM" on top right of webUI seems to not change colours. They act as the same theme.

Hm, i will need to test the standalone version to figure out why.

**Comment by sinamics** [comment]
Regards to the theme selection. i tested on my FreeBSD and it works as expected.
Just for clarity, the "system" will use whatever your machine is configured with. If you are on windows and using Dark theme, then "system" will use Dark in ztnet and they will act the same.

**Comment by tinola** [comment]
Ahh, indeed! I'm on windows using dark theme, thx for clarification :)

**Comment by chonglee123456** [comment]
How to configure Custom Planet in the client

**Comment by sinamics** [comment]
@tinola zerotier paths should now be resolved. 
You also need to copy the freebsd mkworld binary to `/usr/local/bin`

See point 8
https://ztnet.network/installation/freebsd#setup-ztnet
