### ISSUE TITLE
[Support]: When authorizing new members, an error message will appear on a white screen

### ISSUE THREAD

**Issue by v808comd** [sinamics/ztnet#147]
### 📝 Describe the Problem You Are Having

Error message >

Application error: a client-side exception has occurred (see the browser console for more information).

Refreshing will restore, but it does not affect usage

### 🔖 Version

0.3.9

### 💻 Operating System

None

**Comment by tinola** [comment]
Well, I can confirm that issue...

What I saw? (I have turned off auto IP assignment, I like to assign IP manually)

1. Join client with your NetworkID, after few seconds we see:

![01](https://github.com/sinamics/ztnet/assets/3160125/620c61a7-f94e-4567-8a60-f0b3bb1a075c)

2. Click OPTIONS and mess is going up like this (state after manual IP assignment):

![02](https://github.com/sinamics/ztnet/assets/3160125/f2b27862-5c3e-4dd8-b3a2-fb1063158793)

3. Assign an IP address, accept it and click on submit (messed) button... I saw this:

![03](https://github.com/sinamics/ztnet/assets/3160125/fd858d06-296b-4e8a-b47d-0daf049e3562)

4. Refresh page and you will see on members table this:

![04](https://github.com/sinamics/ztnet/assets/3160125/de3faab8-3009-40aa-bcaa-f078349aa702)

Now I can authorize the new member and everything is OK.

**Comment by sinamics** [comment]
Thx. Will try to re-create the issue on my side.
