### ISSUE TITLE
How to configure Custom Planet in the client

### ISSUE THREAD

**Issue by chonglee123456** [sinamics/ztnet#155]
### 📝 Describe the Problem You Are Having

How to configure Custom Planet in the client

### 🔖 Version

v0.31

### 💻 Operating System

None

**Comment by sinamics** [comment]
@chonglee123456 Could you elborate on what exactly you need help with?

![image](https://github.com/sinamics/ztnet/assets/7771916/a1dc8ec8-5a64-4e7f-8218-785093821198)
