### ISSUE TITLE
Dockerfile Build Image Error

### ISSUE THREAD

**Issue by jary888** [sinamics/ztnet#166]
![5265258e-1473-4d00-8674-619e8237e979](https://github.com/sinamics/ztnet/assets/90441511/628d2a8b-c0f4-4208-83bd-741384a7cdf7)

**Comment by sinamics** [comment]
Try this command

```bash
DOCKER_BUILDKIT=1 
docker build --build-arg BUILDPLATFORM=linux/amd64 -t ztnet .
```
