### ISSUE TITLE
Can the dashboard also support custom text ?

### ISSUE THREAD

**Issue by jary888** [sinamics/ztnet#167]
![5c268ecc-96c6-443f-8f58-31cf61d94d90](https://github.com/sinamics/ztnet/assets/90441511/aaa89cb2-eb00-47ad-99cf-acebd51787c9)

and "Network Help" ..

**Comment by sinamics** [comment]
Dashboard will be totally re-worked to either include metrics values or some other usefull information.
Those text boxed is just kind of placeholders.
