### ISSUE TITLE
[Support]: Install on debian as standalone

### ISSUE THREAD

**Issue by seanbts** [sinamics/ztnet#171]
### 📝 Describe the Problem You Are Having

Hi,

Well done on a fantastic project and the GUI is brilliant. I'm trying to install on debian as standalone, if i use the command - 
curl -s http://install.ztnet.network | sudo bash

I get the following error - 
bash: line 1: html: No such file or directory
bash: line 2: syntax error near unexpected token `<'
'ash: line 2: `<head><title>502 Bad Gateway</title></head>

Any idea on what i'm doing wrong?
Thanks.

### 🔖 Version

curl -s http://install.ztnet.network | sudo bash

### 💻 Operating System

Debian

**Comment by sinamics** [comment]
Hi
Please try again now.

**Comment by seanbts** [comment]
Perfect, working now, Thanks very much

**Comment by seanbts** [comment]
Just a follow up question - Running the controller behind a Opnsense FW with port 9993 forwarded to the server still gives Relay on all the clients, do you know of any workaround? Have also tried installing upnp on Opnsense but ZT doenst use it,

Thanks

**Comment by sinamics** [comment]
Opening port 9993 usually resolves the relayed status. 
Make sure you dont have any other fw blocking the traffic such as iptables.

Unfortunately, I don't have additional suggestions beyond this
