### ISSUE TITLE
[Support]: cannot create network

### ISSUE THREAD

**Issue by hithamadel2004** [sinamics/ztnet#182]
### 📝 Describe the Problem You Are Having

**Install in ubuntu-23.10
when create network appear message Could not create network! Please try again**
![1](https://github.com/sinamics/ztnet/assets/77021132/128d5509-0379-4fc4-b9a9-9a84481232a9)

### 🔖 Version

Standalone Ubuntu

### 💻 Operating System

Ubuntu

**Comment by hithamadel2004** [comment]
![2](https://github.com/sinamics/ztnet/assets/77021132/c920a59e-d527-4b79-a51a-e31dd66870e7)

**Comment by tinola** [comment]
Did you install `zerotier` package?... Seems you don't have one.

**Comment by sinamics** [comment]
Inspect the logs for your ZeroTier Docker container using `docker logs zerotier`. 
If you've installed ZeroTier directly on the host, remove it to avoid port 9993 conflicts with the Docker container.

**Comment by hithamadel2004** [comment]
> Inspect the logs for your ZeroTier Docker container using `docker logs zerotier`. If you've installed ZeroTier directly on the host, remove it to avoid port 9993 conflicts with the Docker container.

yes 
At first, I installed zerotier because there was a problem with the installation of the command "curl -s http://install.ztnet.network | sudo bash"
I will Remove it and try again

**Comment by tinola** [comment]
I think you have to change `Local Zerotier URL` from `172.16.92.137:9993` to `127.0.0.1:9993` and submit change.

**Comment by hithamadel2004** [comment]
> I think you have to change `Local Zerotier URL` from `172.16.92.137:9993` to `127.0.0.1:9993` and submit change.

thanks , it work when change 172.16.92.137:9993 to 127.0.0.1:9993

**Comment by hithamadel2004** [comment]
Now I will upload this system to VPS , how protect it ?
