### ISSUE TITLE
[Feature Request]: Migrate to Single-Container Setup with Integrated PostgreSQL

### ISSUE THREAD

**Issue by gyzerok** [sinamics/ztnet#193]
Hello there, great job with the project!

### 🚀 Feature Summary

Combine Postgres and ZTNET into a single container

### 📝 Detailed Description

Nothing to add except it is more user-friendly and self-contained. This is how Vaultwarden does it and in my opinion it's a great idea.

### 💡 Willing to Contribute

None

**Comment by sinamics** [comment]
Thank you. 
Not a bad idea. I'll put it on my list.

**Comment by VMCoud** [comment]
Can I also put the zerotier in the container

**Comment by sinamics** [comment]
I believe it's more logical to maintain ZeroTier in a separate container, allowing users to update it independently without having to build a new version of ztnet.

**Comment by VMCoud** [comment]
> I believe it's more logical to maintain ZeroTier in a separate container, allowing users to update it independently without having to build a new version of ztnet.

![微信截图_20231109193411](https://github.com/sinamics/ztnet/assets/59264435/36c5dafa-995c-4f13-9fed-35728677a2e4)
Is it possible to make an online update like this to install zerotier as a binary program?
https://github.com/rafalb8/ZeroTierOne-Static

**Comment by VMCoud** [comment]
The zerotier can be updated directly from the administrator's back office.

**Comment by VMCoud** [comment]
> 谢谢。这不是一个坏主意。我会把它放在我的清单上。

If Postgres is merged into a ztnet container, does rebuilding the ztnet container lose the Postgres data

**Comment by sinamics** [comment]
> If Postgres is merged into a ztnet container, does rebuilding the ztnet container lose the Postgres data

No. Postgres data will be mapped to its own volume outside the container.

**Comment by sinamics** [comment]
I'm open for discussions and would appcreciate your insights. Do you think this decision is straightforward, or are there any scenarios that I might have overlooked? pros, cons.
https://github.com/sinamics/ztnet/pull/195

**Comment by VMCoud** [comment]
> I'm open for discussions and would appcreciate your insights. Do you think this decision is straightforward, or are there any scenarios that I might have overlooked? pros, cons. #195

Can you add an optional environment variable, the server has other projects and Postgres, ztnet in the built-in Postgres, I feel it will add burden to the server!

**Comment by sinamics** [comment]
> Can you add an optional environment variable, the server has other projects and Postgres, ztnet in the built-in Postgres, I feel it will add burden to the server!

Good point. I can implement a check to determine if the `POSTGRES_HOST` is set to anything other than localhost. If so, I'll completely shut down the PostgreSQL server to conserve resources.

**Comment by sinamics** [comment]
> Is it possible to make an online update like this to install zerotier as a binary program?

Everything is possible, it's just a matter of balancing the time it takes to create and the benefits it will provide.

**Comment by luisbandalap** [comment]
> ### 🚀 Feature Summary
> 
> Combine Postgres and ZTNET into a single container
> ### 📝 Detailed Description
> 
> Nothing to add except it is more user-friendly and self-contained. This is how Vaultwarden does it and in my opinion it's a great idea.

Vaultwarden's official image **does not** include postgresql within it, when no database it's specified it creates a SQLite database file.

> I'm open for discussions and would appcreciate your insights. Do you think this decision is straightforward, or are there any scenarios that I might have overlooked? pros, cons. #195

@sinamics please don't embed postgres or at least build two images (one with postgres and another without it)

**Comment by sinamics** [comment]
Can you give me some reason to why not?
Basically, using the integrated postgres is optionally. If you keep the`POSTGRES_HOST=postgres` then the internal postgres db will not be started at all.  

The only drawback as i see it is that the ztnet image will be slighly lager in size.

**Comment by luisbandalap** [comment]
> Can you give me some reason to why not? Basically, using the integrated postgres is optionally. If you keep the`POSTGRES_HOST=postgres` then the internal postgres db will not be started at all.
> 
> The only drawback as i see it is that the ztnet image will be slighly lager in size.

It's just my opinion, I host many services on a VPS (including this one), if I get out of space I have to pay more to get more storage.

Also if we need to run multiple services there's already docker compose. Container design "principles" prefer (not mandatory) one service per image over multiple services.

It would be better (if possible) to add SQLite (or similar) support and use it when no database url is specified (as vaultwarden does).

**Comment by VMCoud** [comment]
Suggest adapting to SQLite

**Comment by tinola** [comment]
> Suggest adapting to SQLite

Please take a look here: https://github.com/sinamics/ztnet/discussions/163 in Discussion section... :)

**Comment by sinamics** [comment]
After reviewing the discussions about integrating PostgreSQL into the ztnet container, it's clear there's no consensus on the benefits of this change. The idea of a single-container setup is interesting, but there are different views on its advantages.

So, I'm closing this issue for now. We might consider it again in the future if there's a clearer need or benefit that fits the project's main goals. For now, let's focus on keeping ztnet stable and scalable.
