### ISSUE TITLE
[Feature Request]: Administrator background settings Default theme Language Languages

### ISSUE THREAD

**Issue by VMCoud** [sinamics/ztnet#199]
### 🚀 Feature Summary

Change language according to browser language

### 📝 Detailed Description

Dashboard and Network Help Multi-language support

### 💡 Willing to Contribute

Yes, I could help with coding

**Comment by sinamics** [comment]
Dashbord will get a complete overhaul at some point, so im not putting down any work for translating that at the moment.
The rest will be translated and default would be to whatever the browser has.
