### ISSUE TITLE
OutboundSMTP relay authentication fails

### ISSUE THREAD

**Issue by lilotter45** [sinamics/ztnet#210]
## Description

I use the OutboundSMTP relay service to send emails from various services. I have been unable to successfully authenticate and send an email from ZTNET via this service. The credentials are verified to be correct and are working with several other applications. I am able to successfully send emails via a different service ([PrivateEmail](https://privateemail.com/)).

The SMTP settings for OutboundSMTP can be found [here](https://support.duocircle.com/support/solutions/articles/5000519466-smtp-settings).

### System details

- Platform: LXC on Proxmox PVE 8.0.4
- OS: Debian 12
- Kernel: 6.2.15.014-pve

### Attempted configurations

- No SSL: connect on ports 25, 587 (not listed on the linked support article but is listed as an option in the user dashboard), 2525, 10025. Result = "Invalid login: 535 5.7.8 Authentication rejected"
- With SSL: connect on ports 465, 10465. Result = "Greeting never received"

**Comment by luisbandalap** [comment]
I can confirm this when i'm trying to use AWS SES or sendgrid. I get same errors using every possible configuration.

As workaround I use this container to connect to SES https://hub.docker.com/r/ixdotai/smtp and relay ztnet emails to it.

**Comment by sinamics** [comment]
This should be resolved, you can test this image if you want.
`sinamics/ztnet:main-f329b75`
