### ISSUE TITLE
[Feature Request]: Webhooks

### ISSUE THREAD

**Issue by tiredofit** [sinamics/ztnet#211]
### 🚀 Feature Summary

Execute webhooks for many actions performed on UI or API

### 📝 Detailed Description

Zerotier has recently released through ZT Central [support for webhooks](https://www.zerotier.com/blog/introducing-zerotier-webhooks/). 

- [] A new machine joins a network
- [] An administrator authorizes or deauthorizes a network member
- [] An administrator changes the network configuration
- [] An administrator changes a member configuration
- [] An administrator creates or deletes a network
- [] An administrator deletes a member
- [] A new user is invited to, removed from, or accepts/rejects an invite to join your organization.

### 🎯 Use Case

Having these sort of hooks opens the door to many possibilities, pared with some sort of Webhook receiver such as n8n or whatever you have in your infrastructure.

### 💡 Willing to Contribute

Yes, I could help with testing

**Comment by sinamics** [comment]
webhooks for organization has been added. 
Im not sure if adding webhooks to private accounts would be beneficial, other than in some cases were users want to get notified if a peer joins a private network.

https://ztnet.network/usage/webhooks
