### ISSUE TITLE
Discover the number of hosts under each network ID

### ISSUE THREAD

**Issue by f18911238888** [sinamics/ztnet#217]
### 🚀 Feature Summary

Discover the number of hosts under each network ID

### 📝 Detailed Description

Hello, how can ADMIN know the number of hosts under each network ID? Thank you.

### 💡 Willing to Contribute

None

**Comment by tinola** [comment]
I don't think you know the concept and how ZeroTier works...
Host will automatically be shown after successful joining the specified network - so there is no need to discover anything.

**Comment by f18911238888** [comment]
How do I limit the number of hosts per registered user
