### ISSUE TITLE
[Support]:  User deletion error

### ISSUE THREAD

**Issue by tiredofit** [sinamics/ztnet#227]
### 📝 Describe the Problem You Are Having

When deleting a user after having them join an Organization and send two test messages the following occurs

```
Invalid `prisma.user.delete()` invocation:

Foreign key constraint failed on the field: `Messages_userId_fkey (index)`
```

### 🔖 Version

0.5.0

**Comment by sinamics** [comment]
This has already been fixed. New version will be out later today
https://github.com/sinamics/ztnet/pull/225
