### ISSUE TITLE
[Feature Request]: Auto generate node names option

### ISSUE THREAD

**Issue by tiredofit** [sinamics/ztnet#248]
### 🚀 Feature Summary

Generate node names similar to network names

### 📝 Detailed Description

This is for discussion, and I believe this won't benefit everyone, so it may be best to be used as a toggle or environment variable.

When connecting a node to a new network, the name is blank, yet the ID is populated. For easier name resolution, and pairing with some of the features regarding DNS since 0.4.x it may be beneficial to auto populate a newly registered node with an auto generated name that could be changed at a later time via the interface or via the API. 

### 🎯 Use Case

This may potentially provide a better user experience while we wait for the zerotier client to allow for passing node names upon registration to a network.

### 💡 Willing to Contribute

Yes, I could help with testing

**Comment by sinamics** [comment]
What if we just add the node ID as the name upon registration?
I can add a option in admin menu to enable this feature. 

> This may potentially provide a better user experience while we wait for the zerotier client to allow for passing node names upon registration to a network.

Are they planning to add this feature in a future release?

**Comment by sinamics** [comment]
Additionally, it's important to note that nodes are not automatically authorized upon registration, except in the case of a public network. The DNS script will only display nodes that have been authorized.

**Comment by tiredofit** [comment]
It's hard to tell what ZT is going to add to their client. Their community forums and sub reddits are very elusive and as well their version control isn't quite active. I'll have to go and do some research for some definitive answers, but I feel this was a part of their roadmap for 2.x.

I'm ok with a node ID switch, that should suffice for now as opposed to having to come up with 'random-names' which may potentially collide.
