### ISSUE TITLE
[Support]: Is it possible to have 2 clients with the same Physical IP to be one the same network?

### ISSUE THREAD

**Issue by ik9999** [sinamics/ztnet#251]
### 📝 Describe the Problem You Are Having

Say i have 2 computers that have same public IP address, but cant connect to each other via LAN. Can i use ztnet to have them in the same network? For me, ztnet displays them as one client.

Is that a zerotier limitation?

### 🔖 Version

v0.5.5

### 💻 Operating System

Debian

**Comment by sinamics** [comment]
That should work just fine. 
Type `zerotier-cli info`  on each computer to see the node ID. This ID will show up in ztnet.
