### ISSUE TITLE
[Support]: ZT2Hosts test failed

### ISSUE THREAD

**Issue by f18911238888** [sinamics/ztnet#258]
### 📝 Describe the Problem You Are Having

Hello, I deployed ZT2Hosts according to the help document and found that ping the Windows client from the ZT2Hosts server can resolve it normally, but it cannot be resolved from the Windows client.

Additionally, how to configure multiple network IDs and perform DNS resolution.

Thank yo
![屏幕截图 2023-12-24 002922](https://github.com/sinamics/ztnet/assets/151608713/f846bec6-75a5-45dc-a5e5-e48608fc867a)
u.

### 🔖 Version

0.55

### 💻 Operating System

None

**Comment by sinamics** [comment]
The changes to the hosts file will only apply to the specific PC where the file was updated. 
To update the Windows hosts file, add the entries to this file
`C:\Windows\System32\drivers\etc\hosts`

**Comment by sinamics** [comment]
> Additionally, how to configure multiple network IDs and perform DNS resolution.

```bash
./zt2hosts.sh <ZONE>:<NETWORK_ID> <ZONE>:<NETWORK_ID> <ZONE>:<NETWORK_ID>
```

**Comment by f18911238888** [comment]
Hello, with your help, I successfully resolved multiple network IDs through DNS and displayed them as successful. However, when executing the ping command, there was only one connection. I'm not sure why, thank you.

**Comment by f18911238888** [comment]
![截图 2023-12-24 061652](https://github.com/sinamics/ztnet/assets/151608713/f05bb74b-8a0f-4c5c-bc15-8d69d0efe506)

**Comment by f18911238888** [comment]
![屏幕截图2 2023-12-24 061823](https://github.com/sinamics/ztnet/assets/151608713/0f7e372b-44f6-46e9-82f7-45cbb625d60a)

**Comment by sinamics** [comment]
not sure i understand. There are two devices in your network ( Demo & Win )
You are only pinging one of them win.ztnet.iiot, the others `win.ztnet.vnet` & `win.ztnet.oit` does not exisit in you hosts file as you specified `ztnet.iiot` as your zone name.

**Comment by f18911238888** [comment]
Thank you, I will continue with the testing and let you know once I have the results

**Comment by f18911238888** [comment]
Test environment:

One Ubuntu server with ZTNET controller installed; Install a zerotier client on a Windows computer and add the network ID of ZTNET; UBUNTU one, install zt2hosts for DNS resolution.

Test results:

The zt2hosts server is functioning properly
![屏幕截图 2023-12-25 124413](https://github.com/sinamics/ztnet/assets/151608713/a3e6796c-cea0-459f-9d6a-9954d7358546)

**Comment by f18911238888** [comment]
WINDOWS client, modified HOSTS file and DNS settings, but unable to effectively resolve with zt2hosts、
![屏幕截图 2023-12-25 122336](https://github.com/sinamics/ztnet/assets/151608713/1965085f-1562-4f09-b2d3-cab779fa8f65)
![屏幕截图 2023-12-25 122458](https://github.com/sinamics/ztnet/assets/151608713/5254a814-775a-4ac5-af92-6623204766a1)

**Comment by f18911238888** [comment]
I don't know what caused the failure，please help

**Comment by f18911238888** [comment]
![屏幕截图 2023-12-25 125657](https://github.com/sinamics/ztnet/assets/151608713/4eb29913-e3a6-4a01-9575-253c42db4202)

**Comment by f18911238888** [comment]
Hello, Merry Christmas. After comparing with the official website, I found that there are differences in the output code (as shown in the figure below). My zt2hosts.sh configuration file is as follows. Please help me check for errors there.
![2023-12-25 203949](https://github.com/sinamics/ztnet/assets/151608713/d27d8370-2c42-450c-b2a7-81abd8b3fb37)
![屏幕截图 ](https://github.com/sinamics/ztnet/assets/151608713/8e784ad1-4848-497d-856d-c04212736b2a)

**Comment by f18911238888** [comment]
#!/bin/bash
# zt2hosts: Contact ZTNET API, and convert a list of authorized network members to hosts(5) format

set -eo pipefail

## -----------------------------------------------------------------------------

# Function to check if the zone name is valid
is_valid_zone() {
  if [[ $1 =~ ^([a-zA-Z0-9]([a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])?\.)+[a-zA-Z]{2,6}$ ]]; then
    return 0 
  else
    return 1
  fi
}

[[ -z "$ZTNET_API_TOKEN" ]] && \
  >&2 echo "ERROR: must set ZTNET_API_TOKEN!" && \
  exit 1

[ "$1" = "" ] && \
  >&2 echo "ERROR: must provide at least one network ID!" && \
  exit 1

## -----------------------------------------------------------------------------
API_ADDRESS=${API_ADDRESS:-"http://43.132.234.82:3000"}
API_URL="${API_ADDRESS}/api/v1"
AUTH_HEADER="x-ztnet-auth: ${ZTNET_API_TOKEN}"

## -----------------------------------------------------------------------------
get_network_info() { curl -sH "${AUTH_HEADER}" "$API_URL/network/${1}/"; }
get_network_members() { curl -sH "${AUTH_HEADER}" "${API_URL}/network/${1}/member/"; }

print_ipv6_id() {
  printf "%s:%s:%s" \
    $(echo "$1" | cut -c1-2) \
    $(echo "$1" | cut -c3-6) \
    $(echo "$1" | cut -c7-10)
}

print_rfc4193() {
  printf "fd%s:%s:%s:%s:%s99:93%s" \
    $(echo "$2" | cut -c1-2) \
    $(echo "$2" | cut -c3-6) \
    $(echo "$2" | cut -c7-10) \
    $(echo "$2" | cut -c11-14) \
    $(echo "$2" | cut -c15-16) \
    $(print_ipv6_id "$1")
}

print_6plane() {
  local TOP=${2:0:8}
  local BOT=${2:9:16}
  local hashed=$(printf '%x\n' "$(( 0x$TOP ^ 0x$BOT ))")

  printf "fc%s:%s:%s%s:0000:0000:0001" \
    $(echo "$hashed" | cut -c1-2) \
    $(echo "$hashed" | cut -c3-6) \
    $(echo "$hashed" | cut -c7-8) \
    $(print_ipv6_id "$1")
}

## -----------------------------------------------------------------------------
ipv4_lines=("127.0.0.1 localhost")
ipv6_lines=("::1 localhost ip6-localhost ip6-loopback")

for NETWORK in $@; do
  mapfile -td \: FIELDS < <(printf "%s\0" "$NETWORK")
  DNSNAME="${FIELDS[0]}"
  NETWORK="${FIELDS[1]}"

  # Check if the zone name is valid
  if [ -n "$DNSNAME" ] && ! is_valid_zone "$DNSNAME"; then
    >&2 echo "ERROR: Invalid domain name '$DNSNAME'"
    exit 1
  fi

  netmembers=$(get_network_members "$NETWORK")
  netinfo=$(get_network_info "$NETWORK")
  
  # check if "error" is in the response
  if [[ "$netinfo" == *"error"* ]]; then
    >&2 echo "ERROR GET Network: $netinfo"
    exit 1
  fi
  
  # check if "error" is in the response
  if [[ "$netmembers" == *"error"* ]]; then
    >&2 echo "ERROR GET Network Members: $netmembers"
    exit 1
  fi

joined=$(echo "$netmembers" | \
  jq '.[] | select(.authorized == true) | 
      { name: (.name | gsub(" "; "_")), id: .id, ips: .ipAssignments }')

  v6conf=$(echo "$netinfo" | jq -c '.v6AssignMode')
  sixplane=$(echo "$v6conf" | jq -r '.["6plane"]')
  rfc4193=$(echo "$v6conf" | jq -r '.rfc4193')

  for entry in $(echo "$joined" | jq -c '.'); do
    nodeid=$(echo "$entry" | jq -r '.id')
    nodename=$(echo "$entry" | jq -r '.name')

    for ipv4_address in $(echo "$entry" | jq -r '.ips[]'); do
      line=$(printf "%s\t%s\t%s" \
        "$ipv4_address" \
        "$nodename.$DNSNAME" \
        "$nodeid.$DNSNAME")

      ipv4_lines+=("$line")
    done
  done

  for entry in $(echo "$joined" | jq -c '.'); do
    nodeid=$(echo "$entry" | jq -r '.id')

    if [ "$rfc4193" = "true" ]; then
      line=$(printf "%s\t%s.%s\t%s" \
        $(print_rfc4193 "$nodeid" "$NETWORK") \
        $(echo "$entry" | jq -r '.name') \
        "$DNSNAME" \
        "$nodeid.$DNSNAME")
      ipv6_lines+=("$line")
    fi

    if [ "$sixplane" = "true" ]; then
      line=$(printf "%s\t%s.%s\t%s" \
        $(print_6plane "$nodeid" "$NETWORK") \
        $(echo "$entry" | jq -r '.name') \
        "$DNSNAME" \
        "$nodeid.$DNSNAME")
      ipv6_lines+=("$line")
    fi
  done
done

## -----------------------------------------------------------------------------

(
  for x in "${ipv4_lines[@]}"; do printf "%s\n" "$x"; done
  for x in "${ipv6_lines[@]}"; do printf "%s\n" "$x"; done
) | column -t

**Comment by sinamics** [comment]
> I don't know what caused the failure，please help

I have not tested this on windows, so i dont know what could be the issue. I will see if i get time later. 


> After comparing with the official website, I found that there are differences in the output code (as shown in the figure below). My zt2hosts.sh configuration file is as follows. Please help me check for errors there.

I will look into that

**Comment by sinamics** [comment]
@f18911238888 the documentation was wrong, updated the example output
