### ISSUE TITLE
[Feature Request]:  Keeping a DNS config domain list

### ISSUE THREAD

**Issue by PovilasID** [sinamics/ztnet#265]
### 🚀 Feature Summary

Keeping a list of domains that were added 

### 📝 Detailed Description

Another drop down with a list of DNS and IPs assigned to it.

### 🎯 Use Case

If you configure DNS and a domain in "Search Domain in IP" the list of domains that are added are not preserved, so you can not check if that domain was already added. DNS config and propagation can take a while, so after configuring and returning to the panel there maybe an issue that particular domain was not added. Also if you want to remove one DNS entry or change it you have clear all of it and if you do not have a list reassigning it may result in some missed domains. 

### 💡 Willing to Contribute

Yes, I could help with testing

**Comment by sinamics** [comment]
Zerotier only supports a single search domain. 
https://discuss.zerotier.com/t/multiple-dns-search-domains/2749/6

api refrence.
https://docs.zerotier.com/service/v1/#tag/network/operation/getNetworks


Allowed structure:
```
"dns": {
  "domain": "zt.example.com",
    "servers": [
    "10.147.20.3"
    ]
},
```
