### ISSUE TITLE
[Support]: Nonresponsive DNS clearing

### ISSUE THREAD

**Issue by PovilasID** [sinamics/ztnet#267]
### 📝 Describe the Problem You Are Having

On click of DNS clear there is no visual feedback

### 🔖 Version

v0.5.6

### 📋 Docker Logs

```shell
⨯ Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production
```

### 💻 Operating System

Ubuntu

### 📚 Any Other Information That May Be Helpful

(Maybe 'bug' template can be added support sounds like more of I am having issues with the config... also discord link is broken )

**Comment by sinamics** [comment]
im not able to reproduce the non-responsive dns behaviour.
Testet with Ubuntu: 
PRETTY_NAME="Ubuntu 22.04 LTS"
`Linux 5.15.0-40-generic #43-Ubuntu SMP Wed Jun 15 12:54:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

and

PRETTY_NAME="Ubuntu 23.10"
`Linux  6.5.0-9-generic #9-Ubuntu SMP PREEMPT_DYNAMIC Sat Oct  7 01:35:40 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

Could you give me your ubuntu version and browser you are using.

> (Maybe 'bug' template can be added support sounds like more of I am having issues with the config... also discord link is broken )

this has been resolved

**Comment by PovilasID** [comment]
I was using  Windows 11 and Chrome version 120.0.6099.129
