### ISSUE TITLE
Please support

### ISSUE THREAD

**Issue by f18911238888** [sinamics/ztnet#288]
### 📝 Inquiry

Hello, two different network IDs are used for interconnection. For example, to connect two network devices, 3d3981e96ffc7c1b and 3d3981e96f459bd1, how to configure them? Please support. thanks

### 🔖 Version

0.58

### 🔧 Deployment Type

- [X] Docker
- [ ] Standalone

### 💻 Operating System

Ubuntu

**Comment by sinamics** [comment]
There’s no way to automatically do this. Each network is it’s own thing.

Your best bet would probably be to either pick one network and have everyone use that.
One other option would be to add a node that’s joined to both networks. You could then configure it as a router between the two networks..


https://discuss.zerotier.com/t/joining-two-zerotier-networks/14692

https://ztnet.network/usage/override_default_route

**Comment by f18911238888** [comment]
Thank you for your response
