### ISSUE TITLE
[Feature Request]: Improvement of organizations

### ISSUE THREAD

**Issue by Mhalkyo** [sinamics/ztnet#290]
### 🚀 Feature Summary

Improvement of organizations

### 📝 Detailed Description

I would like to suggest an improvement for the organization.

I noticed that currently when you create an organization (vpn1) with an admin account (Test1) you can find it in the organization tab in the administration. However, if I create another account still in admin (Test2) I naturally do not have access to the organization that I created with Test1 because I was not invited. But I can't view the organization (vpn1) in the list of organizations with (Test2).

I propose two solutions which can complement:

🔹 I think it could be interesting to display the list of all organizations at least for admins, in case of problems. With an option that allows you to add several network administrators because at present there may no longer be any admins.
🔹 An option that could be added during creation is that the organization is automatically accessible to all users, (in my case it would be useful if all users had access to the networks). Obviously this would not affect whether the network would be public or private but simply for the users of the panel.

### 🎯 Use Case

If we can have an option that allows access to a network to all users of the panel and future users, this would make it possible to manage large networks more simply and quickly.

### 💡 Willing to Contribute

Yes, I could help with testing

**Comment by sinamics** [comment]
> I noticed that currently when you create an organization (vpn1) with an admin account (Test1) you can find it in the organization tab in the administration. However, if I create another account still in admin (Test2) I naturally do not have access to the organization that I created with Test1 because I was not invited. But I can't view the organization (vpn1) in the list of organizations with (Test2).

Currently there is only one Admin, the first user that register. Others will get the "USER" role.
ztnet is not prepared for multi admins

**Comment by Mhalkyo** [comment]
Can all the people who register have access to all the networks simply and quickly? I plan to put around 40 networks and around ten users

> An option that could be added during creation is that the organization is automatically accessible to all users, (in my case it would be useful if all users had access to the networks). Obviously this would not affect whether the network would be public or private but simply for the users of the panel.

This part can be done by giving access to everyone either by default (but it is undoubtedly complicated) or with an option in the organization admin panel by leaving them accessible.

**Comment by sinamics** [comment]
I dont think its a good idea to open up for all users, this would be a safety concern. I think it would be better if users can request access, and have one admin to approve the account. 

I will set this request as pinned. Multi admin feature is definitely something i will add.
