### ISSUE TITLE
[Feature Request]: Can you control whether data transmission in the ZTNet network is encrypted?

### ISSUE THREAD

**Issue by jary888** [sinamics/ztnet#293]
### 🚀 Feature Summary

Encryption control.

### 📝 Detailed Description

That would be great if this feature could be implemented! It would solve the performance bottleneck of embedded hardware devices.

### 💡 Willing to Contribute

None

**Comment by sinamics** [comment]
I've been looking into how to turn off encryption and compression in ZeroTier by using a trusted path in the local.conf file. It looks like this only works when all the devices are on the same physical network and have the same trusted path set up. 
https://docs.zerotier.com/config/#local-configuration-options

Also, I found out that the trusted path feature is going to be removed in version 2.0 of ZeroTier.
https://discuss.zerotier.com/t/trusted-path-problem-with-configuration/3436/2?u=sinamics

Some other discussion on the topic:
https://discuss.zerotier.com/t/zero-tier-is-not-using-all-the-available-bandwidth-available-on-secondary-network-interface/16266/7

Given this, I've decided it's probably not worth setting up something that's going to be discontinued soon.
