### ISSUE TITLE
[Feature Request]: Add connection options

### ISSUE THREAD

**Issue by Mhalkyo** [sinamics/ztnet#294]
### 🚀 Feature Summary

Add connection options to the ztnet dashboard

### 📝 Detailed Description

I offer you a new featurs in terms of connection options on the ztnet bashboard. It would be to add options like Googlz Workspace, this would add a little more security to the connection.

### 🎯 Use Case

This will add new connection options to the dashboard, for more flexibility.

### 💡 Willing to Contribute

Yes, I could help with testing

**Comment by sinamics** [comment]
im not sure i understand your feature request. Ztnet does support oauth for google, but im not familiar with google workspace. 
Could you eloborate?
