### ISSUE TITLE
[Bug]: The planet uses ipv6,

### ISSUE THREAD

**Issue by v808comd** [sinamics/ztnet#295]
### 🐛 Describe the Bug

The planet uses ipv6,

The physical IP in the member list is displayed incorrectly.

### 🔍 Steps to Reproduce

![QQ图片20240118001605](https://github.com/sinamics/ztnet/assets/65583931/cdecaf29-914c-4ba7-89c3-5f0da8741336)

### 🔧 Deployment Type

- [ ] Docker
- [ ] Standalone

### 🖼 Screenshots

![QQ图片20240118001557](https://github.com/sinamics/ztnet/assets/65583931/f8b39525-285a-48af-a5f1-7450dcf43a84)

**Comment by BingMeng** [comment]
docker默认不支持ipv6，这个ip是打洞打出来的ipv4，要用ipv6就开host network模式

实验性ipv6支持也可以，但是建议先熟读网络工程

**Comment by v808comd** [comment]
> docker默认不支持ipv6，这个ip是打洞打出来的ipv4，要用ipv6就开host network模式
> 
> 实验性ipv6支持也可以，但是建议先熟读网络工程

兄弟，但它是好用的，是走了ipv6的，只是显示了docker的自身ip而已。

**Comment by BingMeng** [comment]
> > docker默认不支持ipv6，这个ip是打洞打出来的ipv4，要用ipv6就开host network模式
> > 实验性ipv6支持也可以，但是建议先熟读网络工程
> 
> 兄弟，但它是好用的，是走了ipv6的，只是显示了docker的自身ip而已。

客户端 zerotier-cli peers 查看对端ip

**Comment by sinamics** [comment]
Ztnet getting the physical IP from the zerotier peers object. Do you see the IPv6 address if you type `zerotier-cli listpeers -j` ?
I guess this issue is not related to ztnet, but rather how zerotier is fetching the peers IP.
