### ISSUE TITLE
[Support]: Can the dashboard be hidden until its functions are fully developed.

### ISSUE THREAD

**Issue by v808comd** [sinamics/ztnet#298]
### 📝 Inquiry

Can the dashboard be hidden until its functions are fully developed.

### 🔖 Version

0.5.9

### 🔧 Deployment Type

- [ ] Docker
- [ ] Standalone

### 💻 Operating System

None

**Comment by sinamics** [comment]
dashboard is the very next thing on the list, so hopefully it will have some usefull info in the uppcoming releases.
