### ISSUE TITLE
Increase input field size in member table

### ISSUE THREAD

**Issue by sinamics** [sinamics/ztnet#306]
Good day.
Can this field be made a little larger?
I indicate a comment there, but it is not visible.
![image](https://github.com/sinamics/ztnet/assets/97723224/d24a891c-6ea2-4f09-a9c6-82900110ce2a)

_Originally posted by @PhaNtomBek in https://github.com/sinamics/ztnet/discussions/305_

**Comment by PhaNtomBek** [comment]
![image](https://github.com/sinamics/ztnet/assets/97723224/3cb39b89-0d1b-4165-85cc-40c5c4f13971)
The problem persists. Reducing the text size does not solve this problem.
