### ISSUE TITLE
[Feature Request]: Issuing API tokens via API

### ISSUE THREAD

**Issue by FallenChromium** [sinamics/ztnet#308]
### 🚀 Feature Summary

Issue API tokens from API (endpoint with email and password auth?)

### 📝 Detailed Description

Thanks for the great project! The amount of polish and eye candy is a pleasant surprise for such a tool :) 

I would like to be able to issue an API token without interacting with ZTNET UI so, I want to use an API for this. Sadly I didn't find any docs for this, so I believe this is not an option at the moment. 

For this to work we'd have to add an endpoint that authenticates user using e-mail and password, because the user might have no tokens at all, which is true in my case. It might be tricky to integrate it since currently nextauth is responsible for this and I am not sure whether it's a common practice to create such endpoints, I want to hear back from you on what do you think about it.

### 🎯 Use Case

Here's the usecase I am trying to accomplish: I am trying to set up a network controller with ztnet and zerotier on a Raspberry Pi using Ansible. For that to be reproducible, idempotent and fully automated, I have to:
- register the admin in ztnet
- create a network
- join it from a Raspberry Pi host OS 
- authorize the new member in the network. 
 
I have problems with getting the ztnet token which is required for everything but registering, and I didn't want to tamper with zerotier container itself (though it looks like an option). I didn't find any options to d

### 💡 Willing to Contribute

Yes, I could help with testing

**Comment by sinamics** [comment]
We could add a new param `createApiToken` to the [Create New User](https://ztnet.network/Rest%20Api/User/post-new-user) endpoint, that will return an api key. This will only be allowed if no users exist.

Then you could use this token in ansible to the rest of your provisioning.

**Comment by djschny** [comment]
@FallenChromium were you ever able to get this running on a raspberry pi? I'd prefer/love that installation method.
