### ISSUE TITLE
[Feature Request]: Create cron job script

### ISSUE THREAD

**Issue by tinola** [sinamics/ztnet#313]
### 🚀 Feature Summary

refresh members status in background

### 📝 Detailed Description

Reflecting to https://github.com/sinamics/ztnet/discussions/311, it would be good if a simple script running for eg. every 5 minutes in the background updated the status of network members in the ztnet database.

### 💡 Willing to Contribute

Yes, I could help with testing

**Comment by tinola** [comment]
Hi,

Just works OK, but only when network is attached to the local controller.
When network is in organization, then cron job seems to not work.

**Comment by sinamics** [comment]
yeah, orgs has not been implented to the cron job. 
Thx for reporting, will check it out.
