### ISSUE TITLE
[Support]: Fetch failed from localhost?

### ISSUE THREAD

**Issue by Caian** [sinamics/ztnet#316]
### 📝 Inquiry

I'm starting a brand new instance of ztnet using podman instead of docker. I have set `NEXTAUTH_URL_INTERNAL=http://localhost:3000`, but I'm still facing error when trying to sign-in:

```
[next-auth][error][CLIENT_FETCH_ERROR] 
https://next-auth.js.org/errors#client_fetch_error fetch failed {
  error: {
    message: 'fetch failed',
    stack: 'TypeError: fetch failed\n' +
      '    at Object.fetch (node:internal/deps/undici/undici:11730:11)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
    name: 'TypeError'
  },
  url: 'http://localhost:3000/api/auth/session',
  message: 'fetch failed'
```

How is this possible?

### 🔖 Version

v0.5.10

### 🔧 Deployment Type

- [X] Docker
- [ ] Standalone

### 💻 Operating System

Other

**Comment by sinamics** [comment]
In your environment, it seems ztnet cannot reach the session API using localhost. 
Testing with `docker exec ztnet curl http://localhost:3000/api/auth/session` likely results in a "Failed to connect" message.

To solve this, you might want to use the container's name or the server's IP address, depending on your Docker network setup. Try `docker exec ztnet curl http://ztnet:3000/api/auth/session`. 
If successful, set `NEXTAUTH_URL_INTERNAL` to `http://ztnet:3000` in your configuration.

**Comment by Caian** [comment]
Thanks, using ztnet worked!
