### ISSUE TITLE
[Bug]: Token expired, but still usable

### ISSUE THREAD

**Issue by tinola** [sinamics/ztnet#343]
### 🐛 Describe the Bug

I found, that expired API token is still active and usable.

![token](https://github.com/sinamics/ztnet/assets/3160125/cbd32736-2d66-434b-b1c0-2e0a45a8ff39)

On this screen personal token should be inactive since 10 minutes.

### 🔍 Steps to Reproduce

Create test token, change "expiresAt" value in database to few minutes in the future, wait until expires, refresh ztnet User settings page, check status of API token (eventually column "isActive" in database).

### 🔧 Deployment Type

- [ ] Docker
- [X] Standalone

### ✨ Expected Behavior

Status "isActive" of API token should be changed to False when expiration date and time has passed.

**Comment by sinamics** [comment]
Thank you again for the testing, much appreciated. 🌟 
Will be fixed.

**Comment by tinola** [comment]
I can confirm as of https://github.com/sinamics/ztnet/commit/930a260d522022eafc4ce8134c394bc73c3b617a the API token status has been changed to **False** and is not usable any more.

```
{
  "error": "Token expired"
}
```

Cheers!
