### ISSUE TITLE
[Bug]: Webhook modal popup

### ISSUE THREAD

**Issue by tinola** [sinamics/ztnet#348]
### 🐛 Describe the Bug

Latest main of course ;)

I found that we can't select webhook actions from drop down menu.

![webhook](https://github.com/sinamics/ztnet/assets/3160125/7c0c1d65-7144-427b-94a5-3c2c9c748e13)

### 🔍 Steps to Reproduce

Try to select webhook action as shown on screenshot

### 🔧 Deployment Type

- [ ] Docker
- [x] Standalone

**Comment by sinamics** [comment]
which browser do you use?

**Comment by tinola** [comment]
latest Firefox

**Comment by sinamics** [comment]
Thank you ⭐

**Comment by tinola** [comment]
Now it works! Thx again =)
