### ISSUE TITLE
[Feature Request]: Select user group for invitation links.

### ISSUE THREAD

**Issue by Mhalkyo** [sinamics/ztnet#353]
### 🚀 Feature Summary

Improvement of groups

### 📝 Detailed Description

It would be interesting to improve the group system. Currently they allow you to define a limited number of networks to create. But it would be nice to be able to choose a group when creating an invitation link. This allows, once the person has created their account, to have direct access to their group without having to intervene. Even more so if we also had the possibility of adding a group to an organization. Cerla would allow when a person creates an account they are assigned to a group which allows them to access an organization.

### 🎯 Use Case

Use while creating an account with the invite link. And upstream configuration for group configuration.

### 💡 Willing to Contribute

Yes, I could help with testing

**Comment by sinamics** [comment]
Ive added groups to invitation links, but not included the organization part.
