### ISSUE TITLE
[Feature Request]: When there are many lines of content, it will be dazzling

### ISSUE THREAD

**Issue by v808comd** [sinamics/ztnet#354]
### 🚀 Feature Summary

managed routers fix

### 📝 Detailed Description

![image](https://github.com/sinamics/ztnet/assets/65583931/88cefeb0-3152-4beb-9a44-49d185fea3e3)
When there are many lines of content, it will be dazzling. Hopefully, when you hover over the content of this row, it will be highlighted.

### 💡 Willing to Contribute

Yes, I could help with testing

**Comment by v808comd** [comment]
It would be perfect if it could be modified and sorted.

**Comment by sinamics** [comment]
Will add background color when hover for now.
