### ISSUE TITLE
[Support]: Ask everyone, after upgrading to v0.6

### ISSUE THREAD

**Issue by v808comd** [sinamics/ztnet#365]
### 📝 Inquiry

When the physical IP of a member changes, it always shows "relay“ unable to connect and the physical IP in the member list cannot be updated?

### 🔖 Version

0.6

### 🔧 Deployment Type

- [ ] Docker
- [ ] Standalone

### 💻 Operating System

None

**Comment by sinamics** [comment]
Its not possible to get the physical ip when a node has relay status, it has to be DIRECT.
ztnet gets the IP from the peers object, and you can check yourself by typing `zerotier-cli listpeers -j`
When relay, the path is an empty array.

**Comment by v808comd** [comment]
I deleted the container and volume. Then re "Docker Compose up - d".
After rejoining each member, there is still one member displayed as "RELAYED".
But other members can directly connect to this member, as can be seen from the ping value.
And its global IP address can be seen in the "listpeers j" of other members

**Comment by sinamics** [comment]
if you type `zerotier-cli listpeers -j` on the controller, do you see the peers object with the public IP for the node that has relayed status?

**Comment by v808comd** [comment]
docker exec -it zerotier ash 
zerotier-cli listpeers -j
Unable to see its public IP address

**Comment by sinamics** [comment]
then its not related to ztnet, as the controller does not have the public ip for that particular node.

**Comment by v808comd** [comment]
Agree with you

**Comment by v808comd** [comment]
Zerotier has a bug.
When adding a memorable new IP to a member and it is already pingable. Then delete the automatically generated management IP, and the newly added IP cannot be connected.

**Comment by tinola** [comment]
It's not `ztnet` related bug at all!
Please submit issue [here](https://github.com/zerotier/ZeroTierOne/issues).
