### ISSUE TITLE
label color mismatch

### ISSUE THREAD

**Issue by tinola** [sinamics/ztnet#368]
https://github.com/sinamics/ztnet/blob/33526966181f1fb8d4a83d5e89b15b4ffed6b5b2/src/components/organization/inviteByMail.tsx#L44

Organization - invite by e-mail label - "text-gray-600" - is it needed?
On the right side (invite  by users) there is text-gray-500 inside `<p>` tag.

**Comment by sinamics** [comment]
you are right, its not needed.

**Comment by tinola** [comment]
🥇
