### ISSUE TITLE
[Bug]: Organization Invite user missing page title

### ISSUE THREAD

**Issue by tinola** [sinamics/ztnet#370]
### 🐛 Describe the Bug

There's no page title :)

### 🔍 Steps to Reproduce

Visit invitation page in your organization

### 🔧 Deployment Type

- [ ] Docker
- [ ] Standalone

**Comment by sinamics** [comment]
Good catch, thank you.

**Comment by tinola** [comment]
Well, I haven't got the page title after the last upgrade from main repo...
Title remains as "`https://my_url:port/pl/organization/<orgId>/invite/`"

**Comment by sinamics** [comment]
Hmm, its working fine in my side

**Comment by tinola** [comment]
Hmm, I built ztnet `main` from scratch...
Standalone version on FreeBSD. Still I haven't got title on this page.
Tried in FF and Edge browser. No luck. WTF? ;)

If it matters... Before building ztnet as standalone in FreeBSD, I have to correct `package.json` file to upgrade `next` from `14.0.3` to `14.1.0`, then I have to manually upgrade `prisma` to the latest one (from v5.8.0 we have got FreeBSD 14 included), and finally I have to correct `node_modules/next/dist/build/swc/index.js` file to force using `-wasm` version of `swc`.

**Comment by sinamics** [comment]
i will test the next version you refer to, it might have some new changes related to the head section.

**Comment by sinamics** [comment]
i tried to update :
```json
"next": "^14.1.4",
"prisma": "^5.11.0",
```

it works just fine.
Would these version work on FreeBsd, or do you need version 14.1.0 or is the latest version ok by you?
I will do some more testing and if everything works ok i will update ztnet to use these versions.

**Comment by tinola** [comment]
Just upgraded to mentioned versions, still no title on invitation page. Straaaaange =)
