### ISSUE TITLE
[Feature Request]: UI improvements 

### ISSUE THREAD

**Issue by PovilasID** [sinamics/ztnet#373]
### 🚀 Feature Summary

Minor UI imrovements

### 📝 Detailed Description

- [x] a) Reducing horizontal margins on network view. While scaled on laptop it results in horizontal scroll bar if menu is open, so I would  just ditch .sm:w-5/6 class as wrapped on it or reduce the margins to something like 9/10. A toggle for full with could be as compromise when working on desktop vs laptop people.

- [x] b) STASH button in the list view. Having to select 'Options' for every item I need to stash gets annoying especially after migrating a larger network to the UI with lots of old clients. Multi select could fix but it could get confusing with auth cheeks in front. Also Stach could use an inline description.

- [ ] c) Inline/onclick IP add. my.zerotier.com having the option to just enter a specific IP and add it is very nice while testing doing subnet migration for peers and allows for fast switch back.

- [x] d) Mode indicators. If I select "Do Not Auto-Assign IPs" it is not visually represented in the list view. Could be an icon indicator. Same with bridging. 

- [x] e) Visual indicator for unassigned networks. If local controlled gets a new network from CLI or API it does not show up if not assigned and some direction to could be nice. 

- [x] f) Network ID copy button in network list view. I find it copying ids from that list then sharing. An invite button jumping to invite section for network would also be nice.

- [x] g) Pressing the logo should return to local controller. I am as used to that as back button.

- [x] e) Stupid color theme. I like how professional this tool looks but not having an option for offensive option like cyber punk or something obnoxiously gothy is just missed opportunity. Considering https://daisyui.com/theme-generator/

Let me know if any of them you agree with.

### 🎯 Use Case

Listed next to the point.

### 💡 Willing to Contribute

Yes, I could help with coding

**Comment by sinamics** [comment]
Agree with most of these points.

b) The reason i put the stash button in option modal was to make the table more dense and to avoid the scrollbar. 
    I think we should add a extended table view option with or without inline buttons and ip management ect. 
 
c, d, e) same as above.

**Comment by PovilasID** [comment]
Then I have some time I will try to add some those changes.

Another small addition could be:

Network QR codes. There could be and extra button next to copy ID to show QR code or down my the email invite.
QR codes can be scanned in at least Android Zerotier in the app down by the network settings. It just URL QR code:
`https://joinzt.com/addnetwork?nwid=NETWORK_ID&v=1` (replace NETWORK_ID with the ID)

**Comment by sinamics** [comment]
> QR codes can be scanned in at least Android Zerotier in the app down by the network settings

Im also on android, but i cannot see the qr scanner?
Which version of zt are you on?

**Comment by PovilasID** [comment]
> > QR codes can be scanned in at least Android Zerotier in the app down by the network settings
> 
> Im also on android, but i cannot see the qr scanner? Which version of zt are you on?

It is in the "Add network" view. It is not explicit that it is a button.
ver 1.12.0-5
![image](https://github.com/sinamics/ztnet/assets/396243/0d87c265-c1e0-43f4-9961-5245be7f00d9)

**Comment by sinamics** [comment]
im on the 12.0-3 and does not have the qr button.
This is the latest version as well..

**Comment by PovilasID** [comment]
> im on the 12.0-3 and does not have the qr button.
> This is the latest version as well..

I subscribed to beta track of the app.
