### ISSUE TITLE
[Support]: Unable to register user / log in

### ISSUE THREAD

**Issue by RorbinS** [sinamics/ztnet#377]
### 📝 Inquiry

Have tried several installs of ZTNET, all of them experiencing the same problem. Once the installer script has sun and claims the WebUI is functioning, I try creating a new user, which just sits and spins on the "sign up" button forever after clicking. Trying to log in with the supplied user credentials always results in no login taking place, and the error message "Failed to Fetch" popping up in the bottom right. 

### 🔖 Version

0.6.0 / 0.5.11

### 🔧 Deployment Type

- [ ] Docker
- [X] Standalone

### 💻 Operating System

Ubuntu

**Comment by sinamics** [comment]
Make sure the NEXTAUTH_URL in the /opt/ztnet/.env file has the correct server IP

**Comment by RorbinS** [comment]
> Make sure the NEXTAUTH_URL in the /opt/ztnet/.env file has the correct server IP

And what would this be exactly? I currently have it set to the FQDN of the instance, http://URL:3000

This is the default behaviour of the ZTNET installer

**Comment by sinamics** [comment]
Fqdn is correct, but If you are using reverse proxy you need to remove the port number 3000. 

It should be the url pointing to the ztnet installation. 

If you still have issues, try adding in `NEXTAUTH_URL_INTERNAL=http://localhost:3000`

**Comment by RorbinS** [comment]
Using FQDN, no proxy in place. Have added the NEXTAUTH_URL_INTERNAL=http://localhost:3000 flag after the NEXTAUTH_URL line in the env file, no change (still getting "Failed to Fetch")

**Comment by sinamics** [comment]
you should be able to curl the ztnet api using 
```bash
curl -i http://localhost:3000/api/auth/session/
```

This command should respond HTTP 200 OK. 
If not, try your server ip instead of localhost.

NextAuth uses this API for authentication, and it relies on the value set for NEXTAUTH_URL to determine where to send authentication requests.

**Comment by RorbinS** [comment]
`admrobins@vps-b4f93ede:~$ curl -i http://localhost:3000/api/auth/session/
HTTP/1.1 200 OK
Set-Cookie: next-auth.csrf-token=[REDACTED]; Path=/; HttpOnly; SameSite=Lax
Set-Cookie: next-auth.callback-url=http%3A%2F%2Fkiri.skrdt.net%3A3000; Path=/; HttpOnly; SameSite=Lax
Content-Type: application/json; charset=utf-8
ETag: "[REDACTED]"
Content-Length: 2
Vary: Accept-Encoding
Date: Tue, 02 Apr 2024 09:18:40 GMT
Connection: keep-alive
Keep-Alive: timeout=5`

So, the fact the curl succeeded means it is working?

**Comment by sinamics** [comment]
Yes. so adding `NEXTAUTH_URL_INTERNAL=http://localhost:3000` should work.
Did you restart ztnet server after changing the .env file?
`sudo systemctl restart ztnet`

**Comment by RorbinS** [comment]
Yes, I did a service restart, even a full server restart. Still no luck on the web GUI.

`Last login: Tue Apr  2 09:18:15 2024 from 92.40.170.110
admrobins@vps-b4f93ede:$ sudo systemctl status ztnet
[sudo] password for admrobins:
● ztnet.service - ZTnet Service
     Loaded: loaded (/etc/systemd/system/ztnet.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2024-04-01 20:19:11 UTC; 13h ago
   Main PID: 612 (next-server)
      Tasks: 15 (limit: 2251)
     Memory: 152.2M
        CPU: 3.109s
     CGroup: /system.slice/ztnet.service
             └─612 next-server "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""

Apr 01 20:19:11 vps-b4f93ede systemd[1]: Started ZTnet Service.
Apr 01 20:19:12 vps-b4f93ede node[612]:    ▲ Next.js 14.0.3
Apr 01 20:19:12 vps-b4f93ede node[612]:    - Local:        http://localhost:3000
Apr 01 20:19:12 vps-b4f93ede node[612]:    - Network:      http://0.0.0.0:3000
Apr 01 20:19:13 vps-b4f93ede node[612]:  ✓ Ready in 450ms


admrobins@vps-b4f93ede:$ sudo systemctl restart ztnet


admrobins@vps-b4f93ede:$ sudo systemctl status ztnet
● ztnet.service - ZTnet Service
     Loaded: loaded (/etc/systemd/system/ztnet.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2024-04-02 09:38:50 UTC; 2s ago
   Main PID: 12021 (next-server)
      Tasks: 11 (limit: 2251)
     Memory: 50.6M
        CPU: 624ms
     CGroup: /system.slice/ztnet.service
             └─12021 next-server "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""

Apr 02 09:38:50 vps-b4f93ede systemd[1]: ztnet.service: Consumed 3.118s CPU time.
Apr 02 09:38:50 vps-b4f93ede systemd[1]: Started ZTnet Service.
Apr 02 09:38:50 vps-b4f93ede node[12021]:    ▲ Next.js 14.0.3
Apr 02 09:38:50 vps-b4f93ede node[12021]:    - Local:        http://localhost:3000
Apr 02 09:38:50 vps-b4f93ede node[12021]:    - Network:      http://0.0.0.0:3000
Apr 02 09:38:50 vps-b4f93ede node[12021]:  ✓ Ready in 145ms


admrobins@vps-b4f93ede:$ sudo cat /opt/ztnet/.env
DATABASE_URL=postgresql://ztnet:[REDACTED]@127.0.0.1:5432/ztnet?schema=public
ZT_ADDR=http://127.0.0.1:9993
NEXT_PUBLIC_SITE_NAME=ZTnet
NEXTAUTH_URL=http://kiri.skrdt.net:3000
NEXTAUTH_URL_INTERNAL=http://localhost:3000
NEXT_PUBLIC_APP_VERSION=v0.5.11
NEXTAUTH_SECRET=[REDACTED]
admrobins@vps-b4f93ede:$`

**Comment by sinamics** [comment]
try `NEXTAUTH_URL_INTERNAL=http://127.0.0.1:3000`

**Comment by RorbinS** [comment]
No change. CURL still succeeding, web panel still loading but still giving "Failed to Fetch" error trying to login, Trying to create the user account still reports that the email address is taken.

**Comment by sinamics** [comment]
I just tested to register at http://kiri.skrdt.net:3000, at it worked just fine.

**Comment by RorbinS** [comment]
Then there's something very fundamentally wrong somewhere, because I just tried 3 different email addresses and get the same issue every time.

**Comment by RorbinS** [comment]
Further to this, I have tested on another computer, using Edge, and the computer I've been having issues with, in Firefox. For whatever reason, the Vivaldi browser on Windows will not function correctly with ZTnet. Login works fine in Firefox / Edge.

**Comment by RorbinS** [comment]
Not sure if the user agent would be a factor in this, but Vivaldi reports as Chrome:

`"Chromium";v="122","Not(A:Brand";v="24","Google Chrome";v="122"`

**Comment by sinamics** [comment]
I test Edge, Chrome, Firefox in development.. 
I'm not familiar with Vivaldi, so I'm unsure if it will work. 

> Login works fine in Firefox / Edge.

So you are able to login now?

**Comment by RorbinS** [comment]
Yes, I can log in now. 

For context, this is the error generated when pressing the "login" button. 

`Error: Callback for provider type credentials not supported`

Which is requested from the URL http://kiri.skrdt.net:3000/api/auth/callback/credentials

Not sure if there's any extra info that could be useful, but I'll likely raise this with the Vivaldi dev team to investigate, as it clearly isn't expected behaviour given this is proven to work in other Chromium browsers.
