### ISSUE TITLE
[Bug]: Member list - disallow stashing CONTROLLER

### ISSUE THREAD

**Issue by tinola** [sinamics/ztnet#385]
### 🐛 Describe the Bug

Hi,

I think the "STASH" button next to CONTROLLER member **should not be shown at all** (in popup modal options as well).

BTW, if we have (since v0.6.2) shash button next to every network member, we can delete this button in member options popup modal...

### 🔍 Steps to Reproduce

-

### 🔧 Deployment Type

- [ ] Docker
- [ ] Standalone

**Comment by sinamics** [comment]
> I think the "STASH" button next to CONTROLLER member should not be shown at all.

Why not? The controller is just a client and we should allow to remove it from a network.

> BTW, if we have (since v0.6.2) shash button next to every network member, we can delete this button in member options popup modal...

Agree.

**Comment by tinola** [comment]
> Why not? The controller is just a client and we should allow to remove it from a network.

Basically I haven't tested this. I am not sure whether this will not end in unexpected problems with the network operations when the controller is stashed.

**Comment by sinamics** [comment]
Stashing the controller will not affect anything related to the controller side of things.
