### ISSUE TITLE
[Feature Request]: There are still a few small expectations.

### ISSUE THREAD

**Issue by v808comd** [sinamics/ztnet#386]
### 📝 Inquiry

I'm glad to see that this software is getting better and better. There are still a few small expectations.
1. I hope to add an unchanged identifier for each user, so that administrators can find the corresponding user through the unchanged identifier. Only management can modify this identifier, and the identifier does not need to be visible to users.
2. I hope to display the user's registration and expiration time in the table. It can be sorted by registration time and expiration time.

![61432d84-b5d9-4ac2-88b5-d306393a6988](https://github.com/sinamics/ztnet/assets/65583931/5637a39e-8982-458d-b793-9f88f0f5f5ac)

### 🔖 Version

0.62

### 🔧 Deployment Type

- [ ] Docker
- [ ] Standalone

### 💻 Operating System

None

**Comment by sinamics** [comment]
> I hope to add an unchanged identifier for each user, so that administrators can find the corresponding user through the unchanged identifier. Only management can modify this identifier, and the identifier does not need to be visible to users.

We can show the user ID, a 25char identifier, but this value can not be changed.
If admins can change a user identifier, then its not a "unchanged identifier"!
