### ISSUE TITLE
[Feature Request]: Layer 2 Bridge support 

### ISSUE THREAD

**Issue by ipv6next** [sinamics/ztnet#388]
### 🚀 Feature Summary

Create a new ZeroTier network  througt Layer 2 Bridge 

### 💡 Willing to Contribute

None

**Comment by sinamics** [comment]
I'm not sure I understand your feature request properly, but this to me looks like a ZeroTier service-related question? If you're asking for ZeroTier to support Layer 2 bridging capabilities?

**Comment by ipv6next** [comment]
yes , ZeroTier has supported  Layer 2 bridging capabilities. Can ztnet implement this feature

**Comment by sinamics** [comment]
I will look into it when time permits.

**Comment by dsm150** [comment]
> yes , ZeroTier has supported Layer 2 bridging capabilities. Can ztnet implement this feature

Ztnet is essentially a graphical shell for some of zerotier's functions. The question is incorrectly posed. Ethernet bridging must be supported by the device on which the zerotier client is installed. For example, Mikrotik routers, OpenWRT and any Linux distribution have no problems with this.
Here is an article from the official support site:
[Layer 2 Bridge](https://docs.zerotier.com/bridging/)
Note that all bridge functions are performed by the device in the network, but not by the controller. In theory, you can make the controller perform this function, but I would not do that. The controller should ONLY perform the controller function.

I use multiple networks with Mikrotik as an L2 bridge between the LAN and Zerotier clients. All of this is under the control of a Ztnet controller. Everything works fine. Again, the Layer 2 routing capability is built into the Zerotier itself. All you need to do on the controller is to check Allow Bridging in the settings of the client acting as an L2 bridge. And of course follow the instructions from the article above.

**Comment by sinamics** [comment]
thx @dsm150, i agree and this is out of scope for ztnet interface. 
Closing this issue.
