### ISSUE TITLE
Number of planet servers?

### ISSUE THREAD

**Issue by drno88** [sinamics/ztnet#389]
### 📝 Inquiry

Good afternoon. Please tell me, is it possible to add more than 4 planet servers? Now when creating it an error is thrown
"2024/04/27 08:18:41 root nodes are too many."

Is this a Zerotier limitation or does it apply to your project?

Thank you

### 🔖 Version

latest

### 🔧 Deployment Type

- [X] Docker
- [ ] Standalone

### 💻 Operating System

Ubuntu

**Comment by sinamics** [comment]
This is a limitation in mkworld binary for creating roots.
https://github.com/kmahyyg/ztncui-aio/blob/e75b5cb9468e35713436ae0d243703b42a3da2f1/ztnodeid/pkg/node/world.go#L26

**Comment by drno88** [comment]
> This is a limitation in mkworld binary for creating roots. https://github.com/kmahyyg/ztncui-aio/blob/e75b5cb9468e35713436ae0d243703b42a3da2f1/ztnodeid/pkg/node/world.go#L26

It's clear. Thank you for the answer.
Isn't there an easy way to change this value?

**Comment by sinamics** [comment]
you can increase it, but then you need to build a new version of mkworld and replace the one used in ztnet.
