### ISSUE TITLE
[Feature Request]: Get list of all network addresses used in controller

### ISSUE THREAD

**Issue by dsm150** [sinamics/ztnet#391]
### 🚀 Feature Summary

Get list of all network addresses used in controller

### 📝 Detailed Description

As I was able to understand, when creating a new network, the controller does not take into account the addresses of previously created networks, and can create another network with the same address as the existing one.
It would be ideal if each time the controller creates a new network, it would not give out the addresses of the previously created networks.

If this is labor-intensive to implement, it would be sufficient to at least be able to view the list of currently used network addresses.

If there is such a possibility and I have not found it, please help 🙏🏻

### 💡 Willing to Contribute

None

**Comment by sinamics** [comment]
you are correct.  ztnet is selecting a random address when creating network. 
one way to solve this is to use the network index and select a address based on that. 

Example:
- Network 1 => 10.121.15.0
- Network 2 => 10.121.16.0
...

**Comment by dsm150** [comment]
That's understandable.
But how to view already issued addresses for existing networks in one list?
When assigning new ones, I would like to see which ones have already been issued.

**Comment by sinamics** [comment]
for that we need to store the address in db for each network and then do a lookup to get a list of used addresses.

**Comment by dsm150** [comment]
So now the addresses are not stored in the database?
If they are, how can I query the database?
It would be great if clicking on "Total networks" would display a list of networks and their addresses.
![iScreen Shoter - Yandex - 240506211104](https://github.com/sinamics/ztnet/assets/56016218/623c7360-416d-4339-af91-c047091b94d5)

**Comment by sinamics** [comment]
network ip is not stored in db.
https://github.com/sinamics/ztnet/blob/52bd3285de659ff294e32f1f1b09ae013c2ca378/prisma/schema.prisma#L93

**Comment by dsm150** [comment]
At the moment, to find out the addresses of all networks, you have to manually go through each network and write in notepad...
With hundreds of networks, this will become impossible....

Is it possible to do something about this in the future?

**Comment by sinamics** [comment]
Yes, i will add a list of used ip`s in the controller page and the "Ip Assignment" section for each network.
Another nice feature would be to inform users that X network uses the same address as a notification.

**Comment by dsm150** [comment]
Looking forward to the update. It will be excellent!

**Comment by sinamics** [comment]
@dsm150 would this be sufficient enough?

![image](https://github.com/sinamics/ztnet/assets/7771916/d1e8d873-1928-4440-9e8c-a9698440269e)

**Comment by sinamics** [comment]
merged these changes. 
I will add more notifications in the network ip assignement section later on when i get time.

**Comment by dsm150** [comment]
> @dsm150 would this be sufficient enough?
> 

This is already good, but yes, it would be much more convenient if a unique range was generated when creating a new network, or if you could select a range given the existing ones.
