### ISSUE TITLE
[Bug]: Nested subdomains for DNS search domain is invalid

### ISSUE THREAD

**Issue by buiapp** [sinamics/ztnet#404]
### 🐛 Describe the Bug

ZTNET throws an error saying that the domain is invalid when entering a nested subdomain to the Search Domain field. Zerotier actually allows this. Example: `hello.home.arpa` should be valid.

### 🔍 Steps to Reproduce

Enter `hello.home.arpa` to the Search Domain field in the network settings.

### 🔧 Deployment Type

- [X] Docker
- [ ] Standalone

### ✨ Expected Behavior

`hello.home.arpa` should be a valid search domain.

### 🖼 Screenshots

![Untitled](https://github.com/sinamics/ztnet/assets/116504091/56cd91c5-8792-4c72-a8d3-85da461d31f1)

**Comment by sinamics** [comment]
Which version of ztnet do you use?

**Comment by buiapp** [comment]
> Which version of ztnet do you use?

I am using version v0.6.2

**Comment by sinamics** [comment]
This was fixed in version v0.6.3.
https://github.com/sinamics/ztnet/releases/tag/v0.6.3

Do an update and it should work.

**Comment by buiapp** [comment]
Man, thank you very much! Didn't know you pushed an update 6 hours ago. :)
