### ISSUE TITLE
[Feature Request]: UI support for flags in flow rule tags

### ISSUE THREAD

**Issue by lilotter45** [sinamics/ztnet#407]
### 🚀 Feature Summary

Add support in the UI for assigning tag values as flags, in addition to the current capability to assign enums

### 📝 Detailed Description

When creating tags in ZeroTier flow rules, you can create tag values as enums or flags. A single enum can be assigned for each tag, while multiple flags can be assigned for a given tag.

In ZeroTier Central, enums are selected using a dropdown and tags are assigned via checkboxes for each flag value. For example, a tag defined as

```
tag example
  id 1000
  default 0
  enum 100 home
  enum 101 away
  flag 0 apples
  flag 1 oranges
  flag 2 carrots
  flag 3 peas
;
```

Would display as 
![image](https://github.com/sinamics/ztnet/assets/40440358/59db09ab-b515-4f01-b0c1-92a9acaf2764) 
allowing you to select one or more of `apples`, `oranges`, `peas`, and `carrots`.

It appears that ZTNET currently only supports enum tags, displaying them in a dropdown: 
![image](https://github.com/sinamics/ztnet/assets/40440358/f57344d0-9e1d-44bd-8d85-116b14dc8339)

Only the two enums are available as options. Removing the two enums (`home` and `away`) results in no tag values: 
![image](https://github.com/sinamics/ztnet/assets/40440358/3cc59d54-3fd6-4372-9d05-ebf6300c3b43)

The proposed enhancement to ZTNET would display, and allow selection of none or more, flag-type tags in the UI using checkboxes, similar to the implementation in ZeroTier Central. The tag value is assigned in a bitwise manner for each selected flag, e.g. 
- `apples` = 1
- `apples` + `oranges` = 3
- `apples` + `oranges` + `carrots` = 7
- etc.

A greater amount of flexibility in the use of tags in flow rules is afforded through the use of flags in addition to enums, as individual nodes can easily be assigned to multiple "groups" within the tag, enums would limit you to a single group or require the manual creation of an enum for each of the potential combinations.

### 🎯 Use Case

The basic problem this feature would solve is supporting the ability to use functionality that exists within the ZeroTier API via the ZTNET interface.

There are a variety of ways that this feature could be used to implement flow rules for a given network. The use case I was investigating when I found the lack of support was in assigning nodes to one or more groups as a means of managing traffic between nodes, an approach much better documented in [this article](https://alan.norbauer.com/articles/zerotier-rule-groups) than I would manage here.

### 💡 Willing to Contribute

Yes, I could help with testing

**Comment by sinamics** [comment]
Thank you for the detailed PR. 
Could you give docker image `dev-1870523` a go, and see if it works as expected?

**Comment by lilotter45** [comment]
> Thank you for the detailed PR. Could you give docker image `dev-1870523` a go, and see if it works as expected?

I just pulled the image and gave it a try and it works exactly as I would expect, including the relationship between the enum and flag options.

Thanks for such a quick response on this issue and all the work you've done to build a truly useful UI for ZeroTier.
