### ISSUE TITLE
[Bug]: Dropdown menus do not respect default font

### ISSUE THREAD

**Issue by tinola** [sinamics/ztnet#416]
### 🐛 Describe the Bug

Hi :)

Please take a look:

![dropdown_menu](https://github.com/sinamics/ztnet/assets/3160125/017ed3d8-6e82-4ea1-a5cd-40f34e1e1a48)

It seems that every dropdown menu over site is affected - this font looks different than default Inter. It looks like... Times New Roman? :)

### 🔍 Steps to Reproduce

Just expand some dropdown menu.

### 🔧 Deployment Type

- [ ] Docker
- [X] Standalone

**Comment by sinamics** [comment]
seems like this only occurs in Firefox. Will look into it.

**Comment by sinamics** [comment]
There is a bug issue over at Mozilla that is still open, given that it was created 5 years ago.
https://bugzilla.mozilla.org/show_bug.cgi?id=1576820

This wasn't an easy fix, but I managed to set the font for the option text to sans-serif.

**Comment by tinola** [comment]
Thanx! Now it's ok. Mozilla sometimes sucks... sometimes more, sometimes less ;P
