### ISSUE TITLE
[Feature Request]:  Support other db engines

### ISSUE THREAD

**Issue by Kegelcizer** [sinamics/ztnet#423]
### 🚀 Feature Summary

Support other db engines 

### 📝 Detailed Description

As far as I can tell, only postgres is supported.
Would it be possible to add others like mssql, mysql or even sqlite?

### 🎯 Use Case

Hosting on a small cheap VPS that's already near capacity or has a different sql engine instance would be tricky, sqlite or other light alternative would help in this case.

### 💡 Willing to Contribute

Yes, I could help with testing

**Comment by sinamics** [comment]
This has been discussed before (#163) and i will not add support for other Databases.
