### ISSUE TITLE
[Support]: Move from ztncui

### ISSUE THREAD

**Issue by SamKr** [sinamics/ztnet#424]
### 📝 Inquiry

I'm currently using [ztncui](https://key-networks.com/ztncui), which is ok but has outdated looks and isn't actively maintained. I'd love to switch to ztnet as this looks like a great way to go forward. However, I already have a bunch of networks on ztncui. 

Is it at all possible to move them to ztnet, or do I need to recreate them and let the devices join the new network?

### 🔖 Version

n/a

### 🔧 Deployment Type

- [ ] Docker
- [ ] Standalone

### 💻 Operating System

None

**Comment by sinamics** [comment]
Do you use the docker or .deb version of ztncui?

**Comment by sinamics** [comment]
If you have ZeroTier installed locally at your host, you can use this guide to configure ZTNET to use your local ZeroTier instance instead of the ZeroTier container.

https://ztnet.network/usage/migrate

**Comment by SamKr** [comment]
I use the local installed version, so this is perfect! Thanks for the quick help (and of course ZTNET itself) ❤️
