### ISSUE TITLE
[Support]: Add existing network to new Organization

### ISSUE THREAD

**Issue by owopeachy** [sinamics/ztnet#426]
### 📝 Inquiry

Hello, is there a way i can add a network to an organization? I migrated from ztncui to ztnet and would like to use the organization feature but I can't seem to figure out how to add the existing network to the new organization, only add new. Is there a way i can add perhaps manually through postgresql commands or something? Sorry if this was already a closed issue, couldn't find it there

### 🔖 Version

0.6.5

### 🔧 Deployment Type

- [ ] Docker
- [X] Standalone

### 💻 Operating System

Ubuntu

**Comment by sinamics** [comment]
You need to assign network to yourself, then in the network page you can move networks to an organization.

**Comment by owopeachy** [comment]
Thanks found it!
