### ISSUE TITLE
[Support]: Restrict WAN access to port 3000.

### ISSUE THREAD

**Issue by marco-dmaa** [sinamics/ztnet#427]
### 📝 Inquiry

Good morning,

I run ztnet standalone on a VPS running Debian.
All works smooth and you 've done a great work (Thanks!!!).

I got nginx to reverse proxy with Lets' Encrypt SSL Certificates.
All works so when i go to the https port it redirect me to the http port 3000.

But the unsecure port 3000 is still alive e reachable from the WAN.

How can i hide it or bind it only to localhost?

Thanks, Marco.

### 🔖 Version

0.6.5

### 🔧 Deployment Type

- [ ] Docker
- [X] Standalone

### 💻 Operating System

Debian

**Comment by tinola** [comment]
You are absolutely right. That's why I set firewall rule to block connection on this port from WAN.

**Comment by marco-dmaa** [comment]
Yes, but I' working on a VPS, so I cant edit the firewall rules of my provider...

How can I solve it in another way?

**Comment by tinola** [comment]
What provider is this? If you have root access to your VPS then you can set FW rules.

**Comment by marco-dmaa** [comment]
It's on Netsons!

Yes, i have root access. But you mean using iptables?

Thanks, Marco.

**Comment by tinola** [comment]
I don't know what Linux distribution you have, so think `iptables` or `ufw` if we talk about some Debian/Ubuntu dists.
I personally have got `ztnet` running on FreeBSD based bare metal home server, but firewall rules I set on Mikrotik router (RouterOS 7) as it is the first device connected to the WAN.

**Comment by marco-dmaa** [comment]
I have Debian 12 but I'm unsure how to do the rules in iptables...

I can't edit the rules on the provider firewall.

**Comment by tinola** [comment]
Well, I think you have to log in into the VPS terminal text console via SSH. Check if you have access over SSH to ur VPS.
Then issue command something like:

```
# iptables -A INPUT -p tcp --destination-port 3000 -j DROP
# service iptables save
```

You can then check your rules:

`# iptables -L -n -v`
or
`# iptables -L -n -v | grep 3000`

EDIT
Please consider some google investigations, because I wrote above using my mind which can be unreliable ;)
Linux is not my favorite server system, but something I remember how to use it 😆

**Comment by sinamics** [comment]
you can host ztnet at 127.0.0.1 instead of 0.0.0.0 and do the routing in nginx, this way you dont need to worry about the port,

`sudo nano /etc/systemd/system/ztnet.service`

Add line `EnvironmentFile=/opt/ztnet/.env`
E.g
```bash
[Unit]
Description=ZTnet Service
After=network.target

[Service]
EnvironmentFile=/opt/ztnet/.env
ExecStart=/usr/bin/node "/opt/ztnet/server.js"
Restart=always

[Install]
WantedBy=multi-user.target
```

Load configuration
`sudo systemctl daemon-reload`


now you can add `HOSTNAME` to the `/opt/ztnet/.env` file.
e.g
```bash
HOSTNAME=127.0.0.1
```

Restart ztnet
`sudo systemctl restart ztnet`

**Comment by marco-dmaa** [comment]
Thank you @sinamics . I tried your suggestion and it works!!!

And thank @tinola for your support!

Marco.

**Comment by marco-dmaa** [comment]
Good morning, trying what you wrote to me, it doesn't work. It blocks port 3000. Then, through the reverse proxy, I correctly access the login page, but it remains stuck.

**Comment by marco-dmaa** [comment]
Good morning, trying what you wrote to me, it doesn't work. It blocks port 3000. Then, through the reverse proxy, I correctly access the login page, but it remains stuck.

**Comment by marco-dmaa** [comment]
Here the errors in journal:

`Aug 01 10:51:06 vps-debian node[35901]: https://next-auth.js.org/errors#client_fetch_error fetch failed {
Aug 01 10:51:06 vps-debian node[35901]:   error: {
Aug 01 10:51:06 vps-debian node[35901]:     message: 'fetch failed',
Aug 01 10:51:06 vps-debian node[35901]:     stack: 'TypeError: fetch failed\n' +
Aug 01 10:51:06 vps-debian node[35901]:       '    at node:internal/deps/undici/undici:12618:11\n' +
Aug 01 10:51:06 vps-debian node[35901]:       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
Aug 01 10:51:06 vps-debian node[35901]:     name: 'TypeError'
Aug 01 10:51:06 vps-debian node[35901]:   },
Aug 01 10:51:06 vps-debian node[35901]:   url: 'http://XX.XX.XX.XX:3000/api/auth/session',
Aug 01 10:51:06 vps-debian node[35901]:   message: 'fetch failed'
Aug 01 10:51:06 vps-debian node[35901]: }
Aug 01 10:51:06 vps-debian node[35901]: [next-auth][error][CLIENT_FETCH_ERROR]
Aug 01 10:51:06 vps-debian node[35901]: https://next-auth.js.org/errors#client_fetch_error fetch failed {
Aug 01 10:51:06 vps-debian node[35901]:   error: {
Aug 01 10:51:06 vps-debian node[35901]:     message: 'fetch failed',
Aug 01 10:51:06 vps-debian node[35901]:     stack: 'TypeError: fetch failed\n' +
Aug 01 10:51:06 vps-debian node[35901]:       '    at node:internal/deps/undici/undici:12618:11\n' +
Aug 01 10:51:06 vps-debian node[35901]:       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
Aug 01 10:51:06 vps-debian node[35901]:     name: 'TypeError'
Aug 01 10:51:06 vps-debian node[35901]:   },
Aug 01 10:51:06 vps-debian node[35901]:   url: 'http://XX.XX.XX.X:3000/api/auth/session',
Aug 01 10:51:06 vps-debian node[35901]:   message: 'fetch failed'
Aug 01 10:51:06 vps-debian node[35901]: }` 


Thanks, Marco.
