### ISSUE TITLE
[Bug]: Test rest API error:{"message":"You are not a member of this organization. Contact your organization administrator to request access."}

### ISSUE THREAD

**Issue by ipv6next** [sinamics/ztnet#434]
### 🐛 Describe the Bug

[Bug]: Test rest API error:{"message":"You are not a member of this organization. Contact your organization administrator to request access."}

C:\Users\ipv6n>curl -L -X GET "http://ztnet.ipv6next.cn:3000/api/v1/org" -H "Accept: application/json" -H "x-ztnet-auth: 1a5b72766b4d75d79f6f559b2664971f:be6e8be550ac66b9069631ef65939e0a33f2466c98b4d5ed5a8baed0392d6e0a9b1b5e0ee0XXXXX"
[{"id":"clx4ebdd6000ap7iw06zi2x31","orgName":"aaa","ownerId":"clx43g2iy0000p7iwvh2sdv7q","description":"","createdAt":"2024-06-07T07:59:32.967Z"}]
C:\Users\ipv6n>curl -L -X GET "http://ztnet.ipv6next.cn:3000/api/v1/org/:"clx4ebdd6000ap7iw06zi2x31"" -H "Accept: application/json" -H "x-ztnet-auth: 1a5b72766b4d75d79f6f559b2664971f:be6e8be550ac66b9069631ef65939e0a33f2466c98b4d5ed5a8baed0392d6e0a9b1b5e0ee0XXXXXXX"
{"message":"You are not a member of this organization. Contact your organization administrator to request access."}

### 🔍 Steps to Reproduce

according by :
curl -L -X GET 'https://ztnet.network/api/v1/org/:orgId' \
-H 'Accept: application/json' \
-H 'x-ztnet-auth: <API_KEY_VALUE>'

### 🔧 Deployment Type

- [X] Docker
- [ ] Standalone

### 🖼 Screenshots

![image](https://github.com/sinamics/ztnet/assets/135030220/86e2ac26-08a0-402c-bcb0-9f3ca83ca1f7)

**Comment by sinamics** [comment]
```bash
curl -L -X GET "http://ztnet.ipv6next.cn:3000/api/v1/org/:"clx4ebdd6000ap7iw06zi2x31""
```

remove the `:` from the url like this:
```
curl -L -X GET "http://ztnet.ipv6next.cn:3000/api/v1/org/"clx4ebdd6000ap7iw06zi2x31""
```

**Comment by sinamics** [comment]
did you solve this issue?

**Comment by ipv6next** [comment]
i have solved it ,thanks
