### ISSUE TITLE
[Feature Request]: White Label + Azure AD Authentication with roles support

### ISSUE THREAD

**Issue by mvthul** [sinamics/ztnet#443]
### 🚀 Feature Summary

Possibility to Add own logo + site colors. Ability to login with Azure AD. 

### 💡 Willing to Contribute

None

**Comment by sinamics** [comment]
I won't be dedicating time to add options for changing the logo or colors, as there are already many themes to choose from. However, I am happy to review and accept pull requests from anyone who wants to add these features.

I will test the AD login when i get time.
