### ISSUE TITLE
[Bug]: vpn migration

### ISSUE THREAD

**Issue by Mhalkyo** [sinamics/ztnet#444]
### 🐛 Describe the Bug

I tried to migrate the ZTNET VPN, with an export of the database. I carried out this migration on a new machine with a different IP. I reimport the database and put back the three containers. I can connect and I have access to my networks. I'm using a custom route, so I changed the IP of the route to the new IP. I replaced the planet after changing the IP but when I select a network it does not appear, and when I create a network it appears fine but it is impossible to add a computer to it.

![Capture d'écran 2024-06-18 124056](https://github.com/sinamics/ztnet/assets/73218308/4a06e32b-b26d-40b5-9d98-c9909a03c97c)
![Capture d'écran 2024-06-18 124116](https://github.com/sinamics/ztnet/assets/73218308/a782f4b9-eeba-4758-a62d-7d0ecc10d2e8)

### 🔍 Steps to Reproduce

Perform a migration by exporting and importing the database.
Replace the route IP.

### 🔧 Deployment Type

- [X] Docker
- [ ] Standalone

### ✨ Expected Behavior

What would be best is if we could perform a migration on another machine that does not have the same IP. I don't know if there is another alternative or if there is something I'm doing wrong.

### 📋 ZTNET Logs

```shell
I have no error
```

**Comment by sinamics** [comment]
Did you export the zerotier docker volume?
It looks to me that those ztnet networks does not exist on the new zerotier controller, hence the loading screen.

**Comment by Mhalkyo** [comment]
I did an export of the postgresql bss, but I didn't get the volume back. I thought that only the bdd was needed?

**Comment by sinamics** [comment]
You also need to export ZeroTier volume, or at least the /lib/zerotier-one folder, Ztnet is simply a wrapper for the ZeroTier controller, and the networks in the PostgreSQL database must match the existing networks in ZeroTier.

**Comment by Mhalkyo** [comment]
actually by recovering the data from zerotier it works

**Comment by Mhalkyo** [comment]
It's good
