### ISSUE TITLE
[Bug]: Falsely alarm about the duplicate subnet

### ISSUE THREAD

**Issue by Musda** [sinamics/ztnet#457]
### 🐛 Describe the Bug

I have set up two networks through the ZTNET, the IP ranges are:
- 10.10.0.0/16 (Fig. 1)
- 10.20.0.0/16 (Fig. 2)
These two IP ranges do not conflict, but the WebUI told me the range was in conflict. (Fig. 3)

Fig. 1
<img width="500" alt="image" src="https://github.com/sinamics/ztnet/assets/17185656/aeae88c2-1036-4dbb-b62c-97c49808121d">

Fig. 2
<img width="517" alt="image" src="https://github.com/sinamics/ztnet/assets/17185656/f4039769-afd2-44b3-9209-131f4850e13d">

Fig. 3
<img width="495" alt="image" src="https://github.com/sinamics/ztnet/assets/17185656/40a995bc-6f94-4d4b-95db-50562f24167a">

### 🔍 Steps to Reproduce

Create two networks and set both subnets to CIDR /16 in the same /8 subnet.
Like 10.1.0.0/16 and 10.2.0.0/16

### 🔧 Deployment Type

- [X] Docker
- [X] Standalone

### ✨ Expected Behavior

It should not show up a warning like that.

### 📋 ZTNET Logs

```shell
No need
```

### 🖼 Screenshots

Already in description

**Comment by sinamics** [comment]
im not able to re-produce this issue. 
Can you confirm you only have `10.10.0.0/16 via LAN` under managed routes for 10.10 network and same for 10.20 network?
