### ISSUE TITLE
[Support]: Organization Networks slow to load

### ISSUE THREAD

**Issue by cscompton** [sinamics/ztnet#458]
### 📝 Inquiry

When I choose an organizations network, the network page takes 1-2 minutes to finish loading. I'm running a docker image on a 2GB RAM cloud instance. It was working fine before I updated the container image, the previous version didn't have the QR code generated at the top. docker compose logs don't seem to show any errors. Any suggestions would be helpful.

![image](https://github.com/sinamics/ztnet/assets/16457125/cca02faf-bc94-4024-a39a-bede81fae3d6)

### 🔖 Version

0.6.6

### 🔧 Deployment Type

- [X] Docker
- [ ] Standalone

### 💻 Operating System

Ubuntu

**Comment by sinamics** [comment]
There is a ongoing issue on the same topic. #435
I have not been able to reproduce the issue, so any further info such as number of networks, nodes would be appreciated.
