### ISSUE TITLE
[Feature Request]: IPv6 Auto-Assign from Range

### ISSUE THREAD

**Issue by franklynalexander** [sinamics/ztnet#463]
### 🚀 Feature Summary

IPv6 Auto-Assign from Range

### 📝 Detailed Description

ZeroTier central offers the possibility to assign a global v6 address. Ztnet only supports RFC4193 and 6PLANE at the moment. Assigning a global ipv6 address means no NAT is needed when using v6 with a exit node.

See: https://docs.zerotier.com/exitnode/

![image](https://github.com/user-attachments/assets/c8fca8d0-770c-4d7a-b19c-694989462cdf)

### 🎯 Use Case

*Using IPv6 with an exit node without NAT
*Using the IPv6 internet via ZT when the local connection only supports IPv4

### 💡 Willing to Contribute

Yes, I could help with testing

**Comment by sinamics** [comment]
@franklynalexander can you give this version a go, and test if it works as espected?

`image: sinamics/ztnet:dev-4510da8`

**Important!**, do not test in a prod enviroment. This version has many new features that has not been thoroughly tested.

**Comment by franklynalexander** [comment]
Hi I will test as soon as i'm back from vacation.

**Comment by franklynalexander** [comment]
Hi just did some testing and everything seems to work fine.

![image](https://github.com/user-attachments/assets/eaf0bc45-019e-4f6d-9418-4f3825f0ce7d)

Thanks for adding it so quickly.

**Comment by ipv6next** [comment]
> 您好，刚刚做了一些测试，一切似乎都运行良好。
> 
> ![image](https://github.com/user-attachments/assets/eaf0bc45-019e-4f6d-9418-4f3825f0ce7d)
> 
> 感谢您这么快添加它。

how  u do that? docker or other, can u tell me your environment

**Comment by ipv6next** [comment]
there is the problem about it   [#677](https://github.com/sinamics/ztnet/issues/677)
