### ISSUE TITLE
[Bug]: Validation for IPv6 doesn't work

### ISSUE THREAD

**Issue by wgos** [sinamics/ztnet#464]
### 🐛 Describe the Bug

I am unable to add or remove IPv6 addresses or routes from Managed Routes or IP Assignment menus though this is clearly a supported feature when interacting with controller via API.

It's also impossible to delete any routes (including IPv4) if there are IPv6 routes presented

### Managed routes
1. Go to menu
2. Click a "plus" sign
3. Enter a IPv6 route
4. Click Add

### IP assignments
1. Go to menu
2. Click Advanced
3. Add a IPv6 range
4. Click Submit

### 🔧 Deployment Type

- [X] Docker
- [ ] Standalone

### ✨ Expected Behavior

Both of those menus should validate IPv6 successfully as it is supported by ZeroTier Central, ZeroTier Controller API and [ztcui](https://github.com/key-networks/ztncui) where I migrated from

### 🖼 Screenshots

The error I get when interacting with menus
![image](https://github.com/user-attachments/assets/a1d094b2-a581-431c-b19f-bc5c03af8647)

**Comment by wgos** [comment]
Apparently it seems to be the issue with [this](https://github.com/sinamics/ztnet/blob/5e71f7b6e4fc1e3f09db492a20f23974e769d14e/src/server/api/utils/ipUtils.ts#L95) method

I do think this is caused by a lack of distinction between v4 and v6 at lines 97 and 98. The variable is set by the same method for both addresses, which will return `true` if the address is v4 or v6. So, if the address is v4 or v6, the method will always go for the branch `if(isIPv4)` at line 101 and check `prefixNumber` as if it was v4, even if an IPv6 CIDR is supplied

**Comment by wgos** [comment]
Just tested #465 and it works just fine in both menus

**Comment by wgos** [comment]
This should also help with #463

**Comment by sinamics** [comment]
You are absolutely right, the previous code did not work as intended. 
Thank you for the PR, it looks fine to me.
