### ISSUE TITLE
[Support]: I want "zerotier" to run on a remote independent server, how should I configure the local ztnet?

### ISSUE THREAD

**Issue by v808comd** [sinamics/ztnet#472]
### 📝 Inquiry

I want "zerotier" to run on a remote independent server, how should I configure the local ztnet?

### 🔖 Version

0.6.7

### 🔧 Deployment Type

- [ ] Docker
- [ ] Standalone

### 💻 Operating System

None

**Comment by sinamics** [comment]
type in the external ip address in ztnet => controller page.
Add the zerotier secret. You also need to open port 9993 on the zerotier side to make ztnet talk with the controller.

**Comment by v808comd** [comment]
Where can I find the zerotier secret

**Comment by sinamics** [comment]
cat /var/lib/zerotier-one/authtoken.secret
