### ISSUE TITLE
[Support]: 2FA - recovery codes

### ISSUE THREAD

**Issue by tinola** [sinamics/ztnet#482]
### 📝 Inquiry

Hi,

After successful configuration 2FA ztnet offered ztnet-2FA-recovery-codes.txt with 6 codes. That's fine.
I tried to simulate the lack of a 2FA application with 6-digit codes and log in to the account with a recovery code.
Unfortunately, there is probably no such possibility.
When, after logging in with a login and password, the system expects a 6-digit code from the 2FA application, there is a link "Having problems?". This takes you to a form where, after entering the user's email address, we receive an email with instructions on how to reset 2FA, but there is no possibility to log in with a recovery code.
Did I miss something?

### 🔖 Version

latest main

### 🔧 Deployment Type

- [ ] Docker
- [ ] Standalone

### 💻 Operating System

Other

**Comment by sinamics** [comment]
When you type the recovery code, the 2FA will be disabled and you should be able to login using username/password. You then need to configure 2FA from scratch to enable it again.

**Comment by tinola** [comment]
Oh, to much beer ;)
OK, now all is clear and works as you said 👍 
Thx
