### ISSUE TITLE
[Feature Request]: Members table

### ISSUE THREAD

**Issue by tinola** [sinamics/ztnet#486]
### 🚀 Feature Summary

Column "Created" to be removed/moved?

### 📝 Detailed Description

I think the information about when member was created is not so important to be displayed in members table.
We can move "created" info for example to the member's "Options" modal.
In this case we can recover some valuable space in members table, or even insert other more important info (?)
What do you think @sinamics ?...

### 💡 Willing to Contribute

Yes, I could help with testing

**Comment by sinamics** [comment]
i not sure what else to add instead, im tempted to just remove it to gain more free space.

**Comment by tinola** [comment]
Maybe some statistics from metrics.prom file? But I don't remember in which version of ZT it was implemented.

**Comment by sinamics** [comment]
The statistics from the /metrics API are more tailored for clients, with fewer details available from the controller's side.
