### ISSUE TITLE
[Support]: If two or more users are using the same network IP's. What will happen?

### ISSUE THREAD

**Issue by v808comd** [sinamics/ztnet#488]
### 📝 Inquiry

![19](https://github.com/user-attachments/assets/8ca32e75-ccc5-4c3d-85f3-7f4e15072996)

### 🔖 Version

0.6.8

### 🔧 Deployment Type

- [X] Docker
- [X] Standalone

### 💻 Operating System

None

**Comment by sinamics** [comment]
That won't affect anything. Each ZeroTier network is isolated from others, even if they use the same subnet range. You can have multiple networks with identical IP ranges without any conflicts between them.
