### ISSUE TITLE
[Support]: I want to automatically get the corresponding language type data based on the language preference of the visitor's browser.

### ISSUE THREAD

**Issue by v808comd** [sinamics/ztnet#489]
### 📝 Inquiry

I want to automatically get the corresponding language type data based on the language preference of the visitor's browser.

### 🔖 Version

0.6.8

### 🔧 Deployment Type

- [X] Docker
- [X] Standalone

### 💻 Operating System

None

**Comment by v808comd** [comment]
The current login page doesn't seem like this.

**Comment by sinamics** [comment]
Public auth pages are not translated yet. However, as soon as the user is logged in, the preferred (system) language is selected.
