### ISSUE TITLE
[Bug]: Create a network, configure IP allocation, select advanced settings, specify the range start and range end; the corresponding network CIDR does not change.

### ISSUE THREAD

**Issue by chenchunlai** [sinamics/ztnet#492]
### 🐛 Describe the Bug

Create a network, configure IP allocation, select advanced settings, specify the range start and range end; the corresponding network CIDR does not change.

### 🔍 Steps to Reproduce

- Create a virtual network.
- Select IP allocation.
- Choose "Advanced" settings.
- Manually specify the range start and range end, then submit.
- Observe the displayed network CIDR.

### 🔧 Deployment Type

- [X] Docker
- [ ] Standalone

### ✨ Expected Behavior

Expected Result:

Network Start: 10.100.0.1
Network End: 10.100.0.254
Network CIDR: 10.100.0.0/24

### 🖼 Screenshots

Expected Result:
Network Start: 10.100.0.1
Network End: 10.100.0.254
Network CIDR: 10.100.0.0/24

Actual Result:
Network Start: 10.100.0.1
Network End: 10.100.0.254
Network CIDR: 10.121.15.0/24

![Clip_2024-08-15_14-10-00](https://github.com/user-attachments/assets/c396015e-5543-4827-b54d-ee084ce7595d)

**Comment by sinamics** [comment]
This happens because you still have a managed route for `10.121.15.0/24 - LAN`
When you create a new network, ztnet automatically assigns a subnet. When you add your own start and end address, you need to delete the old managed route to get the correct network CIDR.

**Comment by chenchunlai** [comment]
I followed your instructions and conducted the test. As you mentioned, the issue has indeed been resolved. Thank you
