### ISSUE TITLE
[Bug]: latest main, can't get login page

### ISSUE THREAD

**Issue by tinola** [sinamics/ztnet#497]
### 🐛 Describe the Bug

Hi :)

I did clean build of ztnet, but it seems something went wrong.
I'm still getting redirected to `http://localhost:<port>` instead of configured `NEXTAUTH_URL` in `.env` file:

My ztnet `.env` file:
```
DATABASE_URL=postgresql://postgres:postgres@127.0.0.1:5432/ztnet?schema=public
ZT_ADDR="http://127.0.0.1:9993"
ZT_SECRET="abcd_redacted"
NEXT_PUBLIC_SITE_NAME=ZTNET
NEXTAUTH_URL="https://ztnet.mydomain.pl:21xyz"
NEXTAUTH_SECRET="<redacted>"
TZ="Europe/Warsaw"
HOSTNAME=127.0.0.1
```

Before today's "git pull" and build I was able reach `ztnet` UI with URL: `https://ztnet.mydomain.pl:21xyz/auth/login/`
Now it seems to escape proxy and kick me off to URL: `http://localhost:<port>/pl/auth/login`

My ztnet user `.cshrc` in FreeBSD:
```
### for ztnet
setenv PRISMA_CLI_QUERY_ENGINE_TYPE "binary"
setenv PRISMA_QUERY_ENGINE_BINARY "/home/ztnet/ztnet-prisma-self/query-engine"
setenv PRISMA_FMT_BINARY "/home/ztnet/ztnet-prisma-self/prisma-fmt"
setenv PRISMA_SCHEMA_ENGINE_BINARY "/home/ztnet/ztnet-prisma-self/schema-engine"
setenv PRISMA_QUERY_ENGINE_LIBRARY "/home/ztnet/ztnet-prisma-self/libquery_engine.node"
setenv PORT <port other than 3000>
setenv HOSTNAME 127.0.0.1
```

I've recovered ztnet from backup, so I have working UI before your changes ;)

### 🔍 Steps to Reproduce

Please try in your vm running FreeBSD.

### 🔧 Deployment Type

- [ ] Docker
- [X] Standalone

**Comment by sinamics** [comment]
I improved the locale redirects in ztnet. 
This has allways been an issue when running the application tied to localhost and behind proxy, but it became more significant with the addition of translations to the authentication pages.

Try to build the main branch again and see if works now.

**Comment by tinola** [comment]
Thanks! Now it works OK. No problem with login, no redirect to `localhost:port`

By the way - some sort icons alignment behave strange after "created" column was removed...

![sort_01](https://github.com/user-attachments/assets/5fdd3ec3-0ca8-4fa8-9f3d-8c91c9615bab)

or

![sort_02](https://github.com/user-attachments/assets/1434d7f5-e29f-45f2-a8d4-4a0fd360a51a)

**Comment by tinola** [comment]
Thx, sorting works fine now :)
