### ISSUE TITLE
[Bug]: no email notifications work

### ISSUE THREAD

**Issue by tinola** [sinamics/ztnet#524]
### 🐛 Describe the Bug

"Unexpected token u in JSON at position 0" error notification appears, when trying to send a test e-mail or trying to verify my account e-mail address.

### 🔍 Steps to Reproduce

Try to send test e-mail from every available templates. See error 500 (Internal Server Error).

### 🌐 Browser

Firefox

### 🔧 Deployment Type

- [ ] Docker
- [X] Standalone

### 🖼 Screenshots

![error](https://github.com/user-attachments/assets/f3b74413-5461-4f22-bff7-3e6203afecc9)

**Comment by PhaNtomBek** [comment]
I do not have such a problem on V0.6.10 (Docker). All templates are underway to send email and letters are delivered to the mailbox.

**Comment by sinamics** [comment]
@PhaNtomBek these changes @tinola is testing has not been released yet.

**Comment by tinola** [comment]
Well, I'm testing latest main branch, so in your case it may works ok.

**Comment by sinamics** [comment]
@tinola you can give it another try, it think it should be ok now, but will test more during staging for next release.

**Comment by tinola** [comment]
You're the boss! E-mail functionality came back and works like a charm.

But! I have got next catch (yeah, i know... damn tinola investigator ;P)
Earlier we've got 4 available e-mail templates, now we have 7. I had those first 4 ones translated into Polish.
I saw that after last changes in main branch, my translations disappeared from "textarea" form fields.
For tests I used "reset" button to revert default content in all of them, then translated first one (invitation to join network) into Polish again and finally saved overwritten content, however, the e-mail came in defaults (English)...
In free time please test it in your environment.

**Comment by sinamics** [comment]
I will do some testing

**Comment by tinola** [comment]
Latest main, e-mails are coming translated now :) Thx!
