### ISSUE TITLE
[Bug]: Connected devices issue

### ISSUE THREAD

**Issue by tinola** [sinamics/ztnet#526]
### 🐛 Describe the Bug

I found another problem with connected devices.

I logged in from a laptop (Win11) to my account and logged in simultaneously from a second laptop (Win10) with an identical version of Firefox.

On the user settings page, the device is overwritten under one item. If you click the logout button, both sessions on two different devices will be logged out.

### 🔍 Steps to Reproduce

Log in from two different desktop devices with the same browser version.

### 🌐 Browser

Firefox

### 🔧 Deployment Type

- [ ] Docker
- [ ] Standalone

### ✨ Expected Behavior

Each device should be listed as a separate item.

**Comment by sinamics** [comment]
yeah, im aware of that. 
If you got two identiacal browsers and cpu architecture it will generate same device id. 
I can add user IP in the device hash, but this will cause allot of deivces as the mobile changes IP quite often. 

I think if we should improve it, we need to get the Geographic location from the IP and use that in the device hash.
Btw, thank you for testing, much apprecitated.

**Comment by tinola** [comment]
I'm thinking that maybe it would be easier to use the zerotier client id for the hash?...
So to simplify: userIP + ztClientID = deviceHash?... 

EDIT
Or even easier: ztNetworkID + ztClientID = deviceHash ?

EDIT2
Yeah, this above will eventually work in case login in from within ZT network devices, if not, yeah, it's more complex...

EDIT3
Is it somehow possible to get MAC address of client NIC?... This should be unique to generate device hash id :)
https://www.npmjs.com/package/getmac ?

**Comment by sinamics** [comment]
> Is it somehow possible to get MAC address of client NIC?

This is not a trivial task

These are included in the headers from client:
- Browser name and version
- Operating system name and version
- Device type (desktop, mobile, tablet)
- Rendering engine
- IP

Im using the above to generate hash, execpt the IP.

**Comment by tinola** [comment]
Hi,
Huge improvement in latest main! Two different devices with the same arch and browser are recognized as independent ones, so it's very nice.

Let's get a little bit further...
If those 2 devices are connected and active in ZTNET UI at the same time, we should mark both of them them green with status "active now/logged in". Device marked green is the one which we are viewing UI from, but others are marked gray even when logged in and active.

Yes, I know you need some time to achieve that, so let's keep #526 still open :)
Thanks 4 all what you are doing! Much appreciated as well... :)

EDIT
Also... If device is inactive/logged out the "Logout" button should not be displayed, because the device is indeed logged out :)
Going further, we can consider to add the second button next to "logout" to remove such device from known devices

**Comment by sinamics** [comment]
I think the device marked in green should be the current session so It won't make any confusion. Each browser stores the login session as a cookie. We could mark the other devices that has been used for last 5 min in yellow and set a online flag. 

>Also... If device is inactive/logged out the "Logout" button should not be displayed, because the device is indeed logged out 

Even if a device is inactive, it still has the session stored in the browser. If someone was able to hack your account, you want to keep the device in the list for traceability.

>Going further, we can consider to add the second button next to "logout" to remove such device from known devices

The logout button removes the device from the userdevice db table.

**Comment by tinola** [comment]
> I think the device marked in green should be the current session so It won't make any confusion. Each browser stores the login session as a cookie.

> Even if a device is inactive, it still has the session stored in the browser. If someone was able to hack your account, you want to keep the device in the list for traceability.

Ok, your're right and convinced me :)

> We could mark the other devices that has been used for last 5 min in yellow and set a online flag.

Yes, this is a very good idea! 👍

**Comment by tinola** [comment]
Yeah, it seems to work fine. Thx :)

**Comment by tinola** [comment]
I think something is still wrong...
The same device, the same browser, the same IP, but ZTNET added new device.

![cdevs](https://github.com/user-attachments/assets/c2e2af06-9a5b-4f66-b8df-17c29cdc197f)

Hmm...

**Comment by sinamics** [comment]
You need to logout devices and login again to ztnet to update the cookie. 
When you look in Firefox dev console => Application => Cookies, you should see the `next-auth.did-token` has an Expire / Max-Age on 1 year.  Previously this was set to Session.

**Comment by tinola** [comment]
Thx, now is OK! 🥇 

![cookie](https://github.com/user-attachments/assets/abd267ce-b565-4f41-8540-5d7ab5ad661e)
