### ISSUE TITLE
[Bug]: Recently joined Members missing in Network-Members API

### ISSUE THREAD

**Issue by 1cue-jrupp** [sinamics/ztnet#539]
### 🐛 Describe the Bug

If new Members join to a ZT network they are missing in in the Network-Members API for up to 5 Minutes. There seems to be a cache or something that delays everything. If you open the corresponding network in the Web UI this seems to update the cache.

This affects API Endpoints like:
```
GET /network/:networkId/member
POST /network/:networkId/member/:memberId
```

### 🔍 Steps to Reproduce

Join a new Client to a Network (where the client was not authenticated yet) and call the `POST /network/:networkId/member/:memberId` API to authenticate the new member about 10 seconds later. The API responds that the member is not found. It would now take up to 5 minutes, but if you open the corresponding network in the Web UI once, the member is instantly found by the API afterwards

### 🌐 Browser

Chrome

### 🔧 Deployment Type

- [X] Docker
- [ ] Standalone

### ✨ Expected Behavior

New members should be instantly available to the API or there should be a simple API Call to "refresh" the network members as the Web UI seems to do it. Or is there already such an undocumented endpoint?

**Comment by sinamics** [comment]
Thx, will add a fix.

> New members should be instantly available to the API or there should be a simple API Call to "refresh" the network members as the Web UI seems to do it. Or is there already such an undocumented endpoint?

No, such endpoint does not exist.

**Comment by 1cue-jrupp** [comment]
Hi sinamics, thanks, this would be great improvement for our use case! 😊
