### ISSUE TITLE
[Feature Request]: Multiple controllers with failover

### ISSUE THREAD

**Issue by nimaam** [sinamics/ztnet#546]
### 🚀 Feature Summary

Clustering

### 📝 Detailed Description

Dear Sinamics, I want to know is it possible to have mutliple controller instance and use them with failover scenario, and could we use the clustered postgresql and different location controller? 

### 💡 Willing to Contribute

None

**Comment by chonglee123456** [comment]
Can we increase the limit on the number of nodes under each network ID

**Comment by sinamics** [comment]
> is it possible to have mutliple controller instance and use them with failover scenario

You can copy /var/lib/zerotier-one to another computer / controller and start it up, but its important you dont run both at the same time.

> could we use the clustered postgresql

I know some users are deploying ztnet in a k8n cluster.

> could we use different location controller

Yes. you can add a user or ip for the remote controller in admin => controller page.

**Comment by nimaam** [comment]
But automatically failover is the point, and also the another point is the second controller has different IP, how it will work

**Comment by nimaam** [comment]
And I want to know if we have a cluster of controllers to control multiple root server, how if will work, because if the controller one is gone then all the network will now work any more.

**Comment by sinamics** [comment]
> But automatically failover is the point

I’m not planning to implement this feature within the application itself, as I believe it’s something the end user should manage, not the app.

> another point is the second controller has different IP, how it will work

typically, you'd need to set up a load balancer to handle routing between controllers and ensure smooth failover. This would allow traffic to be redirected properly in the event of a failure.

**Comment by TBT-TBT** [comment]
> because if the controller one is gone then all the network will now work any more.

That is not completely the case as far as I know. Preexisting connections will continue to work even with the controller down, it is just that new connections can't be established (e.g. a newly started computer or newly connecting mobile device).

So high availability is certainly useful with ZT, but it isn't that nothing would work anymore in the same instant the controller goes down.

Apart from that: there are enough ways to make sure a service will run, even without support for clustering of the app itself.
