### ISSUE TITLE
[Bug]: Displaying the names of members of a network

### ISSUE THREAD

**Issue by Mhalkyo** [sinamics/ztnet#553]
### 🐛 Describe the Bug

When I put a name on a network member and it goes beyond the input frame, it does not display the entire name and cuts off part of it.

### 🔍 Steps to Reproduce

Enter a name that exceeds the input frame.

### 🌐 Browser

Chrome

### 🔧 Deployment Type

- [X] Docker
- [ ] Standalone

### ✨ Expected Behavior

The name should be displayed in full and not cut off.

### 🖼 Screenshots

![Capture d'écran 2024-09-17 093815](https://github.com/user-attachments/assets/d31359aa-fcef-429b-9608-42648ed9c4e2)

**Comment by sinamics** [comment]
Im not able to replicate the issue. Which version do you use?
