### ISSUE TITLE
[Feature Request]: Multiple controllers

### ISSUE THREAD

**Issue by nimaam** [sinamics/ztnet#560]
### 🚀 Feature Summary

Remote Controllers

### 📝 Detailed Description

Is it possible to have multiple controllers, technically we can cluster the PostgreSQL and also we can publish distributed shared storage to access the data folder in multiple location, but the logic of the controllers is also important, so if we do multiple controllers with this technologies and scenarios then how we can have multiple controllers?

### 💡 Willing to Contribute

None

**Comment by sinamics** [comment]
It should be possible to achieve what you're aiming for, but I haven't tested it myself. 
I suggest asking this question in the ZeroTier community, as they might have experience with this type of configuration.
