### ISSUE TITLE
[Support]: Modify the default user language

### ISSUE THREAD

**Issue by seocgr** [sinamics/ztnet#570]
### 📝 Inquiry

After the user logs in, the default language is set to Chinese, and the next time you log in or change the browser, it will become the default English, how to fix the default language of all users to Chinese?

### 🔖 Version

0.70

### 🔧 Deployment Type

- [ ] Docker
- [X] Standalone

### 💻 Operating System

Debian

### 🌐 Browser

Firefox

**Comment by sinamics** [comment]
By default, ZTNet uses the language configured in the browser. If the selected language is not supported by ZTNet, the fallback will be English.

**Comment by seocgr** [comment]
> By default, ZTNet uses the language configured in the browser. If the selected language is not supported by ZTNet, the fallback will be English.

1. Can I modify the configuration file to let the user log in to the Chinese language by default.
2. I manually changed to Chinese language, and re-login will return to English, my browser is Chinese.

**Comment by sinamics** [comment]
> Can I modify the configuration file to let the user log in to the Chinese language by default.

No, that is not supported.

> I manually changed to Chinese language, and re-login will return to English, my browser is Chinese.

When you change language, it will be stored in the browser localstorage. Next time you login, ztnet will use the `ztnet-language`.
![image](https://github.com/user-attachments/assets/0d8d6c6c-5d4b-4032-ba09-eb8eac1e06b4)

If this is not working, make sure this property is set in localstorage.  Developer Tools => Application => localstorage.
