### ISSUE TITLE
[Feature Request]:  Maximum Root Planets in Private Planet Configuration 

### ISSUE THREAD

**Issue by oneisall8955** [sinamics/ztnet#579]
Hi there,

Thank you for this amazing project! It’s the most visually appealing, user-friendly, and feature-rich ZeroTier controller frontend I’ve ever used.

While using it, I encountered a small issue: when creating a private planet, I reached multiple root planets (more than 4), but the code restricts this to a maximum of 4, resulting in an error during saving.

After reviewing the logs and checking the code, I found that this limitation is controlled by a variable named ZT_WORLD_MAX_ROOTS, which is hard-coded to 4.

https://github.com/sinamics/ztnet/blob/0ad5c35d459f5acc4ac938ec99614b2bc65684c2/ztnodeid/pkg/node/world.go#L26

Would it be possible to make this value configurable through an environment variable?

Thank you for your assistance!

------------------------------------------

![image](https://github.com/user-attachments/assets/38521ec4-02bc-4678-98b4-b1392975e827)

```txt
2024/10/30 09:31:06 startup flag parsed:  true
2024/10/30 09:31:06 config file read.
2024/10/30 09:31:06 config file unmarshalled.
2024/10/30 09:31:06 root nodes are too many.
panic: preflight check failed, internal requirement cannot be satisfied
goroutine 1 [running]:
main.main()
	./main.go:48 +0x1414
```

**Comment by sinamics** [comment]
https://github.com/sinamics/ztnet/issues/389
