### ISSUE TITLE
[Support]: How to upgrade ztnet in standalone debian & Ubuntu

### ISSUE THREAD

**Issue by v808comd** [sinamics/ztnet#608]
### 📝 Inquiry

How to upgrade ztnet in standalone debian & Ubuntu

### 🔖 Version

0.71

### 🔧 Deployment Type

- [ ] Docker
- [X] Standalone

### 💻 Operating System

Ubuntu

### 🌐 Browser

Chrome

**Comment by sinamics** [comment]
https://ztnet.network/installation/linux

**Comment by v808comd** [comment]
I installed version 0.71 at this link address. The page does not mention the method of upgrading the version, only the methods of rolling back and installing specific versions.

**Comment by v808comd** [comment]
thanks
