### ISSUE TITLE
[Bug]: Direct connection speed issue

### ISSUE THREAD

**Issue by Gejinmiao** [sinamics/ztnet#609]
### 🐛 Describe the Bug

The planet was generated through ZTNET, and each client joined through direct connection, but the direct connection cannot reach the actual bandwidth, which is 30Mbps locally. The external client passed the test with less than 10Mbps and has not been very stable, while the server's bandwidth is 300Mbps

### 🔍 Steps to Reproduce

I am very sure that my local bandwidth is not abnormal, and the speed is normal when connected directly through someone else's software

### 🌐 Browser

Chrome

### 🔧 Deployment Type

- [X] Docker
- [ ] Standalone

**Comment by sinamics** [comment]
This is not releated to ztnet, i suggest you open a new issue over at zerotier github.
