### ISSUE TITLE
[Feature Request]: Capabilities Matrix

### ISSUE THREAD

**Issue by marat2509** [sinamics/ztnet#614]
### 🚀 Feature Summary

A Capabilities Matrix to visualize and manage supported features across different ZeroTier networks and devices. The matrix would allow administrators to quickly assess which devices support specific features, protocols, or configurations in the network.

### 📝 Detailed Description

Source: https://www.zerotier.com/blog/using-flow-rules-to-direct-users-to-services/#:~:text=Getting%20More%20Advanced

![image](https://github.com/user-attachments/assets/e0d9895f-f1ea-4566-92e7-4a6e49448def)

### 🎯 Use Case

1. **Advanced Network Configuration**: Administrators could use the **Capabilities Matrix** to expose dynamic configurations. By defining capabilities (e.g., `cap dns`, `cap http`, `cap htpc`, etc.), they can create a set of rules that can be applied to multiple hosts through the ZTNet UI. This allows for more granular control over which services and ports are accessible on different devices, without the need to manually configure each one. For example, enabling the `cap dns` capability would automatically apply the necessary rules to allow DNS traffic, while enabling `cap http` or `cap htpc` would expose HTTP or media server ports, respectively.  

2. **Efficient Rollout of Network Policies**: With capabilities mapped to devices, network administrators can quickly enable or disable specific configurations for large numbers of devices, without needing to manually configure each one. This makes it much easier to deploy new services or restrictions across the network, such as enabling DNS resolution or media streaming, by simply toggling the relevant capabilities.

3. **Security and Access Control**: The capabilities system provides a security model where devices can be restricted to specific ports and services based on their assigned capabilities. For example, a device with `cap dns` can serve DNS traffic but won’t have access to other services unless further capabilities are enabled. Similarly, an admin (`cap admin`) can access all resources, ensuring that only authorized users or devices can access certain network resources.

By using capabilities in this way, ZeroTier offers a powerful, flexible approach to network security and configuration, making it easier to manage complex, dynamic environments.

### 💡 Willing to Contribute

Yes, I could help with testing

**Comment by sinamics** [comment]
you can set cap in the user options.
But if i understand correctly, you want a matrix table to quickly asses all members in a network?

![image](https://github.com/user-attachments/assets/21094124-cad9-4962-994a-e6255daff97e)

**Comment by marat2509** [comment]
Oops, I didn't expect this functionality to be in the device settings, but expected it to appear somewhere below the rules entry field

In that case, I'm closing the issue, since I expected at all that there was no `cap` compatibility at all, although it turns out there is
