### ISSUE TITLE
[Feature Request]: Chinese language support

### ISSUE THREAD

**Issue by v808comd** [sinamics/ztnet#62]
### 🚀 Feature Summary

Chinese language support 

### 📝 Detailed Description

Hello, can you provide Chinese language support? thanks

### 💡 Willing to Contribute

None

**Comment by sinamics** [comment]
Currently, my primary focus is to enhance the core functionalities and stabilize the application features. As soon as this phase is completed, im definitely planning to implement internationalization (i18n) to make the application accessible to a wider user base.

**Comment by sinamics** [comment]
@v808comd Added chinese language in version 0.2.5
https://github.com/sinamics/ztnet/releases/tag/v0.2.5
