### ISSUE TITLE
[Support Request]: What are the client restrictions?

### ISSUE THREAD

**Issue by jary888** [sinamics/ztnet#75]
### 🚀 Feature Summary

client restrictions?

### 📝 Detailed Description

What are the client restrictions?

### 💡 Willing to Contribute

None

**Comment by sinamics** [comment]
Hi
Could you please provide a bit more detail? Are you asking about compatibility, network requirements, usage limitations, access control, hardware requirements, or perhaps licensing restrictions?

**Comment by jary888** [comment]
Sorry, what I mean is the maximum number of client devices that can be added?

**Comment by sinamics** [comment]
ZTNET has no limits in terms of networks and members. 
Zerotier recommendation is max 16,000 devices behind each NAT-managed external IP address.
https://docs.zerotier.com/zerotier/troubleshooting/#recommended-local-network-and-internet-gateway-configuration

`Place no more than about 16,000 devices behind each NAT-managed external IP address to ensure that each device can map a sufficient number of ports.`

**Comment by jary888** [comment]
Sorry, my English is not good. What I mean is the limit on the number of devices in the "List of members"

**Comment by sinamics** [comment]
@jary888 There is no limit.

**Comment by jary888** [comment]
Okay, thank you for your answer.

**Comment by jary888** [comment]
Also, can you provide Docker images for ARM and ARM64? I always report errors when building images forARM and ARM64.

**Comment by sinamics** [comment]
that should be doable as both `postgres` and `zyclonite/zerotier` support arm/v7 and arm64

**Comment by jary888** [comment]
![image](https://github.com/sinamics/ztnet/assets/90441511/71560af7-91fc-4fae-9cae-9e7260bc6524) 

Kernel panic

**Comment by sinamics** [comment]
@jary888 that wont work, i need to build a new version for arm64 first.

**Comment by jary888** [comment]
That's great Thank you very much!

**Comment by sinamics** [comment]
@jary888 just pushed version 0.3.0 with arm64 support. Let me know if it worked for you
https://github.com/sinamics/ztnet/releases/tag/v0.3.0
