### ISSUE TITLE
[Feature Request]: User Groups to Limit Virtual Network Creation

### ISSUE THREAD

**Issue by v808comd** [sinamics/ztnet#80]
### 🚀 Feature Summary

能否这样，用户最好也可以权限分级。

### 📝 Detailed Description

比如
用户组1：只能创建1个虚拟网络。
用户组2：可以创建5个虚拟网络。
.....
用户组5：不限制创建虚拟网络数量。

### 💡 Willing to Contribute

No, I can only suggest the feature but cannot help in development or testing

**Comment by v808comd** [comment]
Is it possible to allow user groups to also have permission ratings
such as
User Group 1: Only one virtual network can be created.
User Group 2: Can create 5 virtual networks.
...
User Group 5: No limit on the number of virtual networks created.

**Comment by sinamics** [comment]
@v808comd Can you try this image and see if this is what you need?
Please test on a staging server, as this version hasn't undergone thorough testing.

```yml
ztnet:
    image: sinamics/ztnet:main-d606db1
````

**Comment by sinamics** [comment]
@v808comd Just pushed version 0.3.3 with user groups.
