### ISSUE TITLE
[Feature] Adding the "last seen" function to the "Conn status" field.

### ISSUE THREAD

**Issue by sinamics** [sinamics/ztnet#83]
I suggest adding the "last seen" function to the "Conn status" field.
This would be a very useful feature

_Originally posted by @dsm150 in https://github.com/sinamics/ztnet/issues/50#issuecomment-1674566565_

**Comment by sinamics** [comment]
The lastseen is not so trivial to get right. 
Its possible to get the correct last time when a member has Direct status, and i could add something like this:

![image](https://github.com/sinamics/ztnet/assets/7771916/6fe7b909-11f1-4d92-828f-6cbf5b831f5b)

Couple of notes:

- When a member has Direct/Relayed status, the lastseen is approx within 5min anyway.
- When relayed, its not possible to get the lastseen status.
- Adding seconds counter to the table could make users confused as many numbers are moving around. Maybe better to add "within last min" or some static text.

**Comment by dsm150** [comment]
This is implemented by @dec0dOS. Super-accuracy is not needed here. It often happens that there is no direct connection with the owner of the device that is connected to the network. For example, in my case, if a device has not appeared on the network for more than two months, I can conclude that the network is no longer needed by this client. And I block it and delete it.
![img-2023-08-11-16-36-43](https://github.com/sinamics/ztnet/assets/56016218/fe5c0ee3-84d4-4b17-8cb0-29a75c784c04)

**Comment by sinamics** [comment]
@dsm150 This behaviour is already implemented.  Or am i missing something?
When a user disconnects, there will be a last seen value.

![image](https://github.com/sinamics/ztnet/assets/7771916/0dba35ef-8902-47cd-9d35-4d7d6a211f3a)

**Comment by dsm150** [comment]
it doesn't look like this on my controller....
![img-2023-08-11-16-50-44](https://github.com/sinamics/ztnet/assets/56016218/c0360f05-49dc-4961-9557-22d1d2f23dc5)

**Comment by sinamics** [comment]
Interesting. 
Which version are you on?

**Comment by dsm150** [comment]
0.3.1

**Comment by sinamics** [comment]
Now i understand why you wanted this feature. :)
I will investigate.

**Comment by sinamics** [comment]
@dsm150 Are you able to open the chrome dev tools ( F12 ) and goto the console tab.
See if there is any errors when viewing the members table.
![image](https://github.com/sinamics/ztnet/assets/7771916/00407914-99e3-4ee1-abc1-50e4b3a69a22)

**Comment by dsm150** [comment]
![img-2023-08-11-17-19-38](https://github.com/sinamics/ztnet/assets/56016218/b83caae2-a8c4-47e0-a9cd-33bad45d25ec)

**Comment by sinamics** [comment]
Im not able to locate the problem. Everything is working on my dev, staging and prod server. 
Could you try to see the docker logs.
`docker logs ztnet`

Also, could you test if the same issue occurs on your phone or another pc?

**Comment by dsm150** [comment]
Yes, I tried it on multiple computers and different browsers. And also on the phone.
Everywhere the situation is the same.

![img-2023-08-11-17-59-21](https://github.com/sinamics/ztnet/assets/56016218/1006b4dc-acaf-4474-aa1e-31986f465951)

If only I have such a problem, I can reinstall the controller from scratch, since I still have it in test operation.

**Comment by sinamics** [comment]
I'll do more testing and try to figure it out.

**Comment by sinamics** [comment]
I might know why.
Has any of your "offline" members been online lately?

I did some minor changes to the lastSeen value a while back, and if these members has been offline for a long time then the lastSeen value might not have been updated properly.

**Comment by dsm150** [comment]
But what about the column heading name? They are different too.
Now I will connect the disconnected ones and check.

**Comment by sinamics** [comment]
> But what about the column heading name? They are different too.

The images was from my dev server, playing arround with the lastSeen header names / values.

If my assumption is correct, then the lastSeen value should resolve itself as soon as they become online/offline again.

**Comment by dsm150** [comment]
> If my assumption is correct

You absolutely right! All OK

![img-2023-08-11-18-50-58](https://github.com/sinamics/ztnet/assets/56016218/3ab37749-d3b7-4aa1-9692-7321fe96fd8f)
