### ISSUE TITLE
An error in Chinese translation

### ISSUE THREAD

**Issue by jary888** [sinamics/ztnet#88]
### 📝 Describe the Problem You Are Having

![1692339153653](https://github.com/sinamics/ztnet/assets/90441511/38f42d2c-722d-47eb-9e6e-3d30d79fbcda)    In the Network Members table
😊

### 🔖 Version

0.3.3

### 💻 Operating System

None

**Comment by sinamics** [comment]
can you please write the correct translation here in the comment field.

**Comment by jary888** [comment]
Replace ‘存储’ with ‘隐藏’

**Comment by jary888** [comment]
![1692341944382](https://github.com/sinamics/ztnet/assets/90441511/41144a96-1d29-464b-b8a9-ad220e74c172)  显示隐藏的成员
