### ISSUE TITLE
[Feature Request]:  Can administrators manage the network of ordinary users?

### ISSUE THREAD

**Issue by jary888** [sinamics/ztnet#89]
### 🚀 Feature Summary

network management

### 📝 Detailed Description

Is it feasible for administrators to directly manage the network of ordinary users?

### 💡 Willing to Contribute

None

**Comment by sinamics** [comment]
Im not going to add this feature.

- If I allow administrators to directly manage users' networks, it might accidentally invade someone's privacy. I take users privacy very seriously, and I don't want to risk it.
- There's this thing called GDPR, which is all about protecting your data. If I added this feature, it might break some of those rules. It's super important to me to follow these rules and keep everyones data safe.

**Comment by jary888** [comment]
Okay, thank you for your answer.
