### ISSUE TITLE
[Support] Failed to update: Network name, Description, Members name

### ISSUE THREAD

**Issue by v808comd** [sinamics/ztnet#92]
HI, I tested and found several issues with the current version

**Comment by sinamics** [comment]
Hello,

To assist you more effectively:

1. **Version Confirmation**:
   - Please confirm you're using version 0.3.3. 
   - If you've tested a version associated with a specific git commit (e.g., `main-{git-commit}`), be aware that there might be database conflicts due to changes in such versions.

2. **Error Details**:
   - Are there any specific error messages you observed?
   - If you're using Chrome:
     1. Press `F12` to open the developer tools.
     2. Navigate to the 'Console' tab.
     3. Provide any red errors or warnings you see, preferably with screenshots.

3. **Docker Logs**: 
   - Please provide the relevant docker logs. You can retrieve them using the command:
     ```
     docker logs ztnet
     ```

**Comment by sinamics** [comment]
also, if you could type `docker logs ztnet` and post the info here would be great

**Comment by v808comd** [comment]
docker-compose.yml 
  
  volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

Is it because the port number is missing?

**Comment by sinamics** [comment]
> Is it because the port number is missing?

No.

Could you please share the logs as mentioned in my previous message? Specifically, the output of `docker logs ztnet` would be very helpful.

**Comment by v808comd** [comment]
root@v808:/opt# docker logs ztnet
psql: error: could not connect to server: Connection refused
        Is the server running on host "postgres" (172.31.255.3) and accepting
        TCP/IP connections on port 5432?
Postgres is unavailable - sleeping
Applying migrations to the database...
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "postgres", schema "public" at "postgres:5432"

13 migrations found in prisma/migrations

Applying migration `20230402192938_`
Applying migration `20230714081023_flow`
Applying migration `20230717095341_tags`
Applying migration `20230717150852_nw_member`
Applying migration `20230723084736_mailoptions`
Applying migration `20230724093114_nw_description`
Applying migration `20230728082722_init`
Applying migration `20230806115334_zt_central`
Applying migration `20230808053939_db_rework`
Applying migration `20230809202431_cascade`
Applying migration `20230811063619_user_options`
Applying migration `20230813195808_user_group`
Applying migration `20230815175550_custom_root`

The following migrations have been applied:

migrations/
  └─ 20230402192938_/
    └─ migration.sql
  └─ 20230714081023_flow/
    └─ migration.sql
  └─ 20230717095341_tags/
    └─ migration.sql
  └─ 20230717150852_nw_member/
    └─ migration.sql
  └─ 20230723084736_mailoptions/
    └─ migration.sql
  └─ 20230724093114_nw_description/
    └─ migration.sql
  └─ 20230728082722_init/
    └─ migration.sql
  └─ 20230806115334_zt_central/
    └─ migration.sql
  └─ 20230808053939_db_rework/
    └─ migration.sql
  └─ 20230809202431_cascade/
    └─ migration.sql
  └─ 20230811063619_user_options/
    └─ migration.sql
  └─ 20230813195808_user_group/
    └─ migration.sql
  └─ 20230815175550_custom_root/
    └─ migration.sql

All migrations have been successfully applied.
Migrations applied successfully!
Seeding the database...
Environment variables loaded from .env
Running seed command `ts-node --compiler-options {"module":"CommonJS"} prisma/seed.ts` ...
Seeding User Options complete!
Seeding User Options complete!

🌱  The seed command has been executed.
Database seeded successfully!
Executing command
- info Loaded env from /app/.env
Listening on port 3000 url: http://c7fe8d03c813:3000
- info Loaded env from /app/.env

**Comment by sinamics** [comment]
Thank you. 
Could you try to change the network name, and then run the logs again?
Also include logs from the postgres db as well.

`docker logs postgres`

And then 

`docker logs ztnet`

**Comment by v808comd** [comment]
I switched to Centos7 Docker version 24.0.2 for testing. The problem remains. The netstat command can now display port 5432. Modifying the network name is also invalid.

The logs for 'Docker logs ztnet' have not changed.


[root@localhost opt]# docker logs postgres
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... UTC
creating configuration files ... ok
running bootstrap script ... ok
sh: locale: not found
2023-08-19 19:06:09.568 UTC [30] WARNING:  no usable system locales were found
performing post-bootstrap initialization ... ok
syncing data to disk ... ok


Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data -l logfile start

initdb: warning: enabling "trust" authentication for local connections
initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
waiting for server to start....2023-08-19 19:06:09.956 UTC [36] LOG:  starting PostgreSQL 15.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
2023-08-19 19:06:09.957 UTC [36] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-08-19 19:06:09.961 UTC [39] LOG:  database system was shut down at 2023-08-19 19:06:09 UTC
2023-08-19 19:06:09.964 UTC [36] LOG:  database system is ready to accept connections
 done
server started
CREATE DATABASE


/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*

waiting for server to shut down....2023-08-19 19:06:10.082 UTC [36] LOG:  received fast shutdown request
2023-08-19 19:06:10.084 UTC [36] LOG:  aborting any active transactions
2023-08-19 19:06:10.085 UTC [36] LOG:  background worker "logical replication launcher" (PID 42) exited with exit code 1
2023-08-19 19:06:10.085 UTC [37] LOG:  shutting down
2023-08-19 19:06:10.087 UTC [37] LOG:  checkpoint starting: shutdown immediate
2023-08-19 19:06:10.121 UTC [37] LOG:  checkpoint complete: wrote 918 buffers (5.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.007 s, sync=0.023 s, total=0.036 s; sync files=250, longest=0.004 s, average=0.001 s; distance=4222 kB, estimate=4222 kB
2023-08-19 19:06:10.124 UTC [36] LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

2023-08-19 19:06:10.197 UTC [1] LOG:  starting PostgreSQL 15.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
2023-08-19 19:06:10.197 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-08-19 19:06:10.197 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2023-08-19 19:06:10.199 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-08-19 19:06:10.202 UTC [52] LOG:  database system was shut down at 2023-08-19 19:06:10 UTC
2023-08-19 19:06:10.205 UTC [1] LOG:  database system is ready to accept connections
2023-08-19 19:11:10.215 UTC [50] LOG:  checkpoint starting: time
2023-08-19 19:11:30.774 UTC [50] LOG:  checkpoint complete: wrote 208 buffers (1.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=20.545 s, sync=0.010 s, total=20.559 s; sync files=87, longest=0.002 s, average=0.001 s; distance=985 kB, estimate=985 kB
2023-08-19 19:16:10.874 UTC [50] LOG:  checkpoint starting: time
2023-08-19 19:16:10.981 UTC [50] LOG:  checkpoint complete: wrote 2 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.101 s, sync=0.002 s, total=0.107 s; sync files=2, longest=0.002 s, average=0.001 s; distance=2 kB, estimate=887 kB

**Comment by sinamics** [comment]
Thank you for sharing the logs.

I cannot see anything out of the ordinary in the provided logs. To rule out common issues related to user sessions and browsers, please try the following:

1. **Refresh Session**:
   - Log out and then log back in. This helps clear any issues with stale session data.

2. **Browser Checks**:
   - Try using the application in an incognito/private browsing mode.
   - Test with a different browser.

Lastly, can you provide details about:
- Your Operating System.
- The browser you're using.

This will help me get a better understanding of your environment.

**Comment by v808comd** [comment]
Logged out and cleared the cache, and also tried private browsing mode. but the problem persists.

I have tried both Chrome and Edge.
I am using Windows 10

**Comment by v808comd** [comment]
Firefox has also been tested

**Comment by sinamics** [comment]
Thank you for the update.

To further diagnose the issue, let's inspect the browser's Developer Tools, specifically the Network and Console tabs. This will help identify any failed requests or errors that might be causing the problem. Here's a step-by-step guide on how to do this in Chrome:

1. **Open Developer Tools**:
   - Right-click anywhere on the web page and select `Inspect` from the context menu. Alternatively, you can press F12
   
2. **Navigate to the Network Tab**:
   - In the Developer Tools window that appears, click on the `Network` tab.

3. **Reload the Page and Test Changing the Network Name**:
   - With the Network tab open, perform the action of changing the network name on your page. Look for a request with name `network.networkName?batch=1`, it should look something like this:
       ![image](https://github.com/sinamics/ztnet/assets/7771916/b6d033bc-09b8-415a-9c09-a701c38b096c)


4. **Identify Failed Requests**:
   - Look for any entries in the Network log that are colored red or have a status other than `200` or `304`. These could indicate issues.
   
5. **Provide the Details**:
   - Click on any problematic request to view its details and provide a screenshoot.

6. **Check the Console Tab**:
   - Next, click on the `Console` tab in the Developer Tools. Look for any red error messages or warnings. Please share these errors, as they can offer clues about the issue.

**Comment by v808comd** [comment]
Oh my god, it's my habit. I thought typing characters would take effect by clicking elsewhere...... The result is that only 'enter' is needed. It's taking up so much of your time. I'm really sorry about it.   Wuwu

**Comment by sinamics** [comment]
Glad you solved it. 👍 
I could probably add a note "hit enter to save".
