### ISSUE TITLE
[Support]: Building planet  Unable to update the content of the input box

### ISSUE THREAD

**Issue by v808comd** [sinamics/ztnet#96]
### 📝 Describe the Problem You Are Having

How can these three input boxes be updated after inputting characters? I tried clicking on other places with the mouse and it couldn't be updated. If I press Enter, it will be submitted directly.

![ff20230821000048](https://github.com/sinamics/ztnet/assets/65583931/6fde8d37-e426-43a6-bd8e-4a2362b56994)

### 🔖 Version

0.33

### 💻 Operating System

None

**Comment by sinamics** [comment]
The "generate private root" will be improved in the next release. Im doing all the pre-release testing now. 
But to answer you question, when you press submit or hit enter you will submit the current values in the input fields.

![image](https://github.com/sinamics/ztnet/assets/7771916/9a868521-edf1-43fd-a711-8e5df8b68e6b)

**Comment by sinamics** [comment]
@v808comd  Please test `v0.3.4` that has just been released.
https://github.com/sinamics/ztnet/releases/tag/v0.3.4

**Comment by v808comd** [comment]
> 请测试刚刚发布的。 https://github.com/sinamics/ztnet/releases/tag/v0.3.4`v0.3.4`

谢谢  好的，我现在就测试

**Comment by v808comd** [comment]
![ff20230821000048](https://github.com/sinamics/ztnet/assets/65583931/6fa81bb9-5154-4934-a911-cad02d2d8244)
Error assigning user to group: Could not create planet file. Please make sure your config is valid.

If you don't add ipv6, there is no problem.

**Comment by v808comd** [comment]
![331](https://github.com/sinamics/ztnet/assets/65583931/4cb768cf-1377-4094-a1d4-0dda1395a829)
By the way, what is this used for? I haven't learned it yet.

**Comment by sinamics** [comment]
> Error assigning user to group: Could not create planet file. Please make sure your config is valid.

Ah, thx for pointing that out. I will push a new version with a patch. 

> By the way, what is this used for? I haven't learned it yet.

`plID` (Planet ID): This represents a unique identifier for a "planet" or a specific network world in the system. It's crucial to distinguish between different network worlds or "planets".  When you're creating your own, it's important to ensure it's unique to avoid conflicts.

`plBirth` (Planet Birth): This is essentially a timestamp that indicates when a particular "planet" or network world was created or came into existence. It's represented in milliseconds since the Unix epoch (from January 1, 1970). It's a good way to keep track of the chronological order of world creations.

The combination of these values ensures that each network world or "planet" is uniquely identifiable and can be referenced or accessed accordingly in the system.

**Comment by sinamics** [comment]
@v808comd just pushed a fix for the ipv6 address. `v0.3.5`
https://github.com/sinamics/ztnet/releases/tag/v0.3.5

**Comment by v808comd** [comment]
Pretty good, adding ipv6 can create a "plant".
But I only input ipv6, not ipv4. The created plant is not recognizable on the terminal.
![332](https://github.com/sinamics/ztnet/assets/65583931/d2af1b61-b5df-4ffd-b9ce-956f7c3ffa17)

**Comment by BingMeng** [comment]
> Pretty good, adding ipv6 can create a "plant". But I only input ipv6, not ipv4. The created plant is not recognizable on the terminal. ![332](https://user-images.githubusercontent.com/65583931/261914839-d2af1b61-b5df-4ffd-b9ce-956f7c3ffa17.png)

这是zerotier-one的问题，和ui无关

**Comment by v808comd** [comment]
·

> > Pretty good, adding ipv6 can create a "plant". But I only input ipv6, not ipv4. The created plant is not recognizable on the terminal. ![332](https://user-images.githubusercontent.com/65583931/261914839-d2af1b61-b5df-4ffd-b9ce-956f7c3ffa17.png)
> 
> 这是zerotier-one的问题，和ui无关

可是，如果我只使用ipv4地址生成的planet，这里是可以显示出公网ip的。
如果我ipv4和v6都添加上，生成的planet这里只显示ipv4.   
如果我只写了ipv6，这里就显示-1   。应该不是 zerotier-one 的问题。

**Comment by sinamics** [comment]
> But I only input ipv6, not ipv4. The created plant is not recognizable on the terminal.

I currently do not have a definitive answer to address this. This might be a limitation of the mkworld feature or ZeroTier itself. I will need to investigate this further.
